### ISSUE TITLE
It's possible to misunderstand question 49 but still get the right answer

### ISSUE THREAD

**Issue by knatten** [knatten/cppquiz#100]
If you don't know anything about when temporaries are destroyed, and assume they live for the entirety of the enclosing scope like normal local variables, you'll actually arrive at the correct answer.

To demonstrate:

This `main`:
```cpp
int main() {
  C c1(1);
  C c2(2);
}
```

would have the same output as the current `main`:

```cpp
int main() {
  const C &c = C(1);
  C(2);
}
```

**Comment by hextriclosan** [comment]
```
int main() {
  const C &c = C(1);
  C(2);
  C(3);
}
```
should clarify the solution

**Comment by knatten** [comment]
Sorry, I forgot about this one. Fixed now! http://cppquiz.org/quiz/question/49
