### ISSUE TITLE
Question #6 is incorrect

### ISSUE THREAD

**Issue by karthick-gururaj** [knatten/cppquiz#109]
Question 6 (http://cppquiz.org/quiz/question/6) is on the output of

```
int main() {
  for (int i = 0; i < 3; i++)
    std::cout << i;
  for (int i = 0; i < 3; ++i)
    std::cout << i;
}
```

The answer as per quiz is '012012' but the code is UB since `main` doesn't have a return statement. Need to update the code to return a value.

**Comment by knatten** [comment]
I don't think that's true.

According to §3.6.1¶5 in the C++11 standard:
> If control reaches the end of `main` without encountering a `return` statement, the effect is that of executing `return 0;`

If you don't have a copy of the standard to verify this with, you can see a similar rule (with slightly different wording) in the latest draft, which is available for free online: http://eel.is/c++draft/basic.start.main#5
> If control flows off the end of the compound-statement of `main`, the effect is equivalent to a `return` with operand `0` .

Please re-open this issue if you don't agree.

**Comment by karthick-gururaj** [comment]
Thanks - I wasn't aware of this special treatment for `main`. Maybe a note to the following effect in the answer might help those who attempt the quiz:

> If you answered that this program's behavior is undefined due to missing return in `main`, that is not so: If control reaches the end of `main` without encountering a `return` statement, the effect is that of executing `return 0;` as per §3.6.1¶5

**Comment by knatten** [comment]
I don't explicitly return from `main` in any of the questions of the site, and I don't think I want to add that explanation to all the questions. So I think I'll just leave it as it is now.

Anyway, thanks for raising the issue! :)
