### ISSUE TITLE
C++ quiz Question #127 

### ISSUE THREAD

**Issue by bouda6184** [knatten/cppquiz#110]
Compiled on Ubuntu 16.04.4 LTS with command g++ -std=c++11 
output definitely 01000 (checked and rechecked)
Was wondering if answer was a typo or we can expect different output from different compiler?

**Comment by knatten** [comment]
I assume you're using gcc, and not clang? I believe there is a bug in gcc which causes this output, this one in particular: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66672

This issue has been brought up before, and a rather thorough discussion can be found in #96.
