### ISSUE TITLE
Question 117's explanation is not really correct

### ISSUE THREAD

**Issue by Rakete1111** [knatten/cppquiz#114]
The explanation given to Q117 is wrong at worst, misleading at best. I only have a problem with the last paragraph.

It says "a template alias declaration resolve [sic] to a new family of types" but that is wrong. [temp.alias]p1 is quoted, but it actually says:

> An alias template is a name for a family of types.

It doesn't say anything about it being "new".

The actual answer here is unclear, because this is actually a defect ([CWG1286](https://wg21.link/cwg1286)). The standard only says that a specialization of an alias template results in the substitution the of the template parameters into the alias (+SFINAE) and then that it used. But it doesn't say anything about the alias template identifier.

CWG's intent was that the answer of the Q should have been "22". gcc is the only one that follows CWG's intent (clang, edg, msvc do not).

Now my question is: Should this question still exist? It is clearly problematic. I'd recommend saying that the correct answer is "22" as per CWG and that actually, the standard is unclear on this and mentioning the issues and CWG's actual intent as the explanation.

**Comment by knatten** [comment]
Thanks for reporting! The original author of the question never got back to me when I emailed them for clarification, so I did my best to understand it. But I have to admit I never really understood the details of it, so maybe I shouldn't have published it in the first place. Anyway, I've retracted the question now. I don't think we should have questions which depend on clarifications from CWG. 

http://cppquiz.org/quiz/question/117 now has the retracted-warning in case someone ends up on it still:
![screen shot 2018-09-03 at 22 44 30](https://user-images.githubusercontent.com/727543/45001138-f694c680-afca-11e8-9bb0-075b9e53eab1.png)

**Comment by Rakete1111** [comment]
Would it be useful to show an explanation as to why it has been retracted?

**Comment by knatten** [comment]
Yeah, I just hadn't bothered with it yet. Added an issue for it now (https://github.com/knatten/cppquiz/issues/116), but it might be a while until I get to it. Going to prioritise porting the site to C++17 now, it's long overdue.

**Comment by knatten** [comment]
I've now added the possibility for showing a retraction message (PR #133), and added one for this question: http://cppquiz.org/quiz/question/117
