### ISSUE TITLE
Check correctly_answered questions for retracted questions

### ISSUE THREAD

**Issue by vsklamm** [knatten/cppquiz#118]
Do you check `correctly_answered` questions for retracted questions? (training mode)
Will this scenario work correctly?
1. User correctly answered the question #X. His score is `n+1/all` now
2. Question #X was retracted
3. His score is should be `n/all-1` (I think)

UPD:
I check this on question №176, and:

<img src="https://user-images.githubusercontent.com/34794523/45190526-0e787e80-b247-11e8-8587-5936392f31dd.jpg" width="500">

**Comment by knatten** [comment]
I'm sorry I missed this one, this is indeed a bug. `UserData::get_correctly_answered_questions()` in `game_data.py` probably needs to consult `models.Question.objects` and filter out any questions which are not published. We should also add a test in `session_test.py`.

We do `Question.objects.filter(state='PUB')` quite a few places, so maybe we should extract a helper method `published_questions()` or something.
