### ISSUE TITLE
Question #144 

### ISSUE THREAD

**Issue by gravoo** [knatten/cppquiz#139]
I am not quite sure about correctness of that answer. In cppreference we can read:

>  int - basic integer type. ... If no length modifiers are present, it's guaranteed to have a width of at **least 16 bits**. However, on 32/64 bit systems it is almost exclusively guaranteed to have width of at least 32 bits.

So there is no guaranty size of int is 32 bits. Maybe size should be explicit mentioned in the question. 
Anyway the wrong and the right answers "010" are the same for both path in if - else statement.
I suggest changing example code:
```
  else
  {  
    N[1]=1;
  }
```
to e.g.
```
  else
  {  
    N[0]=1;
  }
```

**Comment by knatten** [comment]
I agree that there is no guarantee that the size of int is 32 bits. But the first branch of the `if` doesn't run unless the system is using 32 bit ints:

```cpp
if ( std::numeric_limits<long int>::digits==63 &&
    std::numeric_limits<int>::digits==31 &&
    std::numeric_limits<unsigned int>::digits==32 )
```

If this is true, the answer is `010`. If it's not true, the `else` kicks in, and the answer is still `010`. Does that clarify things?

**Comment by knatten** [comment]
The output of this program is always `010`, no matter how big an `int` (or `unsigned int` and `long int`) is.

**Comment by gravoo** [comment]
Yes I get that.
But my point is, I was wrong during analyzing code. I thought that the answer should be 010 because it will enter "else" branch. Imagine my surprise when I get the 

> Correct! 

with the description: 

> As the else part of the branch is obvious, we concentrate on the if part and make the assumptions present in the condition [...]

**Comment by knatten** [comment]
Right. Are you still suggesting to change anything here? If we change the else branch to do `N[0]=1`, the answer would now be that it's unspecified / implementation defined, and the whole point of the question goes away, since now we're only asking if ints are guaranteed to be 32 bits.

**Comment by gravoo** [comment]
Hmm... Ok if that is the point of this question now I have no objection. I am closing the issue. 
Thank you for your answers :)

**Comment by knatten** [comment]
Cool, thanks! :)
