### ISSUE TITLE
Using https gives a certificate error

### ISSUE THREAD

**Issue by ghewgill** [knatten/cppquiz#140]
Using an https link to the site gives a certificate error:

```
cppquiz.org uses an invalid security certificate.

The certificate is only valid for the following names: *.webfaction.com, webfaction.com

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by knatten** [comment]
Yeah, the site doesn't support https at all. There is no site at https://cppquiz.org/, that url just takes you to a landing page from the webhost.

**Comment by knatten** [comment]
Will set up a redirect from https to http

**Comment by knatten** [comment]
This is now fixed.
