### ISSUE TITLE
Question #228 

### ISSUE THREAD

**Issue by shebdim** [knatten/cppquiz#141]
I can't reproduce this error :( Which compiler can i use to see an error?

**Comment by knatten** [comment]
I tested gcc, clang and msvc now, and they all seem to compile this just fine. Have you seen this error being enforced by any compiler, @Rakete1111?

**Comment by Rakete1111** [comment]
Yeah, it's not a very popular error to report. AFAIK only edg fails to compile the code: https://godbolt.org/z/2gWYd0

**Comment by shebdim** [comment]
> variadic template requires an empty template parameter pack

Hmm,  icc have compiled this code https://godbolt.org/z/MygSbF

**Comment by knatten** [comment]
Yup, most compilers don't report this error.

Can we close the issue, or do you have further questions?

**Comment by shebdim** [comment]
You can close, i think. Thank you!
