### ISSUE TITLE
Q112 explanation

### ISSUE THREAD

**Issue by YehezkelShB** [knatten/cppquiz#143]
> Even though  a  is an rvalue reference

 Seems to me like a typo. `b` is the rvalue reference here.

Additionally, the point is that using this name in the function isn't considered as rvalue usage but as lvalue (rule of thumb: it has a name and isn't used for `return` or with `std::move`? It's an lvalue). (Edit: as explained in Q116)

E.g. when writing move c-tor for derived class, the correct way to invoke base class move c-tor is:
`B(B&& b) : A(std::move(b)), ...`

Accessing a member inside it making it worse as even `return` wouldn't move from it (but I think there are proposals to chnage it in the future).

**Comment by knatten** [comment]
Thanks for the bug report! You're right, it should say `b`, not `a`. I've fixed that now.

I don't really understand where you're going with the rest of your comment. Is there anything else in particular you feel is wrong with question 112, or can I close this issue?

**Comment by YehezkelShB** [comment]
Copying the relevant part of the answer:

> In `B`'s move constructor, `a` is initialized in the initializer list. Even though `a` is an rvalue reference (and bound to an rvalue), `a` itself is an lvalue, and cannot be moved from.

I see 3 issues here:
1. Even though `a` is an rvalue reference - should be `b` (and you fixed this already).
2. `a` itself is an lvalue, and cannot be moved from. - more accurate description would be "when the name `b` is used, it's considered as an lvalue" (which is the point of the rest of my original comment).
3. Just noticed (but very minor if not a nitpicking): *member initializer list* is a better name, to prevent ambiguity with initializer_list. (E.g. https://en.cppreference.com/w/cpp/language/initializer_list)

**Comment by knatten** [comment]
1. yup
2. I think this is what I'm already saying in the explanation? "`b` itself is an lvalue, and cannot be moved from." This is accurate in my opinion. Maybe adding "*The expression* `b` itself is an lvalue" makes it a bit clearer?
2. Absolutely agree! I actually care a lot about this sort of nitpicking for CppQuiz. :) Fixed it now.

**Comment by YehezkelShB** [comment]
2. Oh, now I see the updated version and I see you changed this `a` to `b` too. I thought you changed only one occurrence. OK, so everything is good and we can close this issue now. Thanks for bearing with me here :)

**Comment by knatten** [comment]
Cool, thanks for reporting! :)
