### ISSUE TITLE
Q162 explanation - ICC Behavior

### ISSUE THREAD

**Issue by YehezkelShB** [knatten/cppquiz#144]
The explanation mentions Intel C++ Compiler as matching MSVC behavior. Generally, ICC works hard to match the behavior of the default compiler for the current platform, so I assume this is its behavior on Windows, but on Linux it'll behave like gcc.

**Comment by knatten** [comment]
I'm not sure, the question was contributed by a user. I could try to contact them to clarify, but I'm not sure it's really worth bothering them about?

**Comment by YehezkelShB** [comment]
Up to you how much you care for such info to be as accurate as possible. I agree this isn't the key info of the answer in any way.
But you don't have to bother them, here is a proof for my claim:
https://godbolt.org/z/Wjg0xx
ICC15 isn't available there, but you can see that both v13 and v16 outputs ASCII value 49 (='1') and not 50 (='2'), the same as clang.

**Comment by knatten** [comment]
Ok, thanks! I've added a note now that this behaviour is observed with ICC on Windows in particular.
