### ISSUE TITLE
Q126 explanation - missing colons

### ISSUE THREAD

**Issue by YehezkelShB** [knatten/cppquiz#145]
In two cases there is only one colon there for scope resolution.
btw, in real code, this makes it a label instead of scope name, which can result in a very confusing compilation error or runtime behavior.

**Comment by YehezkelShB** [comment]
BTW, is the content handled in a github project too, where I can submit a PR instead of just opening an issue?

**Comment by knatten** [comment]
Thanks! I've fixed it now.

The content is in a database, not in a repository, so unfortunately it's not possible to make a PR. But thanks for considering doing that! :)
