### ISSUE TITLE
Questions 127's result is incorrect

### ISSUE THREAD

**Issue by kerneltraceroute** [knatten/cppquiz#146]
http://cppquiz.org/quiz/question/127
![image](https://user-images.githubusercontent.com/1964547/50384772-82e20b00-06da-11e9-86ab-7fb1eb8a0005.png)

But this is not the answer to this problem. In g++ with -std=c++17; result **01000**
&& In VS2017 with ISO C++17 Standard (/std:c++17); same result: **01000**

Best Regards

**Comment by robson3** [comment]
The right answer is indeed 01000. j inside a decltype refers to the original j inside main, not to a member of a closure type.

Relevant standard paragraph is here: http://eel.is/c++draft/expr.prim.lambda.capture#11

**Comment by knatten** [comment]
Thanks for reporting! This issue has been brought up several times before, and I've looked into it quite thoroughly. I believe there is a bug in gcc which causes this output, this one in particular: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66672 (I have not checked whether VS has a similar bug report for this.)

A rather thorough discussion of the issue can be found in #96, so I'll close this one as a duplicate.
