### ISSUE TITLE
Perhaps Jupyter with C++ / Cling could be useful

### ISSUE THREAD

**Issue by DrChr** [knatten/cppquiz#151]
Hi,

I enjoyed doing your C++ quizzes and I just want to make sure that you know about _Jupyter_, and that Jupyter can be used with C++/Cling, thus making it useful for a C++ quiz in various ways.

If you've never heard of Jupyter, see [3] below for a demo: The web page might take a while to load the first time, but then it allows you to interactively add, compile and run small snippets of C++ code. This could e.g. be used to show a combination of different variations of C++ snippets, their outputs and explanations. 

cheers,
Christian

Links:
- [1] https://blog.jupyter.org/interactive-workflows-for-c-with-jupyter-fe9b54227d92
- [2] https://github.com/QuantStack/xeus-cling
- [3] https://hub.mybinder.org/user/quantstack-xeus-cling-y1r7qps3/notebooks/notebooks/xcpp.ipynb

**Comment by knatten** [comment]
Thanks for the tip! I've noticed Jupyter before, but never gotten around to really look into it. And I wasn't aware it supported C++! 

I'm not too sure about this use case though, how exactly do you imagine cppquiz taking advantage of this?

**Comment by DrChr** [comment]
I'm not exactly sure to be honest. It'd take some thinking to figure out a good use case if it should still be in quiz like format.  Guess I just have a gut feeling it would be helpful from a teaching point of view to take advantage of being able to interleave explanations with a code snippet that's executed. And even letting the reader modify the code to see what happens when details are changed.

A (randomly chosen) question like http://cppquiz.org/quiz/question/24?result=OK&answer=0&did_answer=Answer that asks about the program's output could perhaps be converted into a Jupyter notebook that shows:
- the question
- the code snippet
- the result of executed code

To see what it'd look like I'll see if I could manually create the above.

**Comment by knatten** [comment]
While the idea is interesting, this sounds like a lot of work compared to what we gain from it. I have very little time to spend on CppQuiz, so I'd prefer to spend that time creating content instead.

**Comment by knatten** [comment]
I'm not going to prioritise implementing this issue. I have however added links to C++ Insights and Compiler Explorer for people to interactively explore the code, hopefully that covers some of the same things. (See #164,  #128)
