### ISSUE TITLE
Add hypertext links into draft of C++17 standard?

### ISSUE THREAD

**Issue by DrChr** [knatten/cppquiz#152]
Hi,

The texts that explains the correct answer are nice to read and often refer into the standard. It'd be convenient if these texts used hypertext links referring into the relevant sections of the C++17 standard.

As far as I know we can't link to the actual standard, but it would be possible to link to a working draft like N4659 of the C++17 standard. See e.g. the SO answer https://stackoverflow.com/a/83763, that refers to the short URL https://wg21.link/std17 which takes you to a PDF version of N4659.  Further, we can use _named destinations_ with that link and thus link directly to e.g. section 5.13 as follows

    http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf#nameddest=section.5.13

It's also possible to link to a specific page and other destinations [*]. 

Converting all references like `[lex.literal]` into section references might be too much work (and fragile when/if switching to the C++20 standard), so perhaps easier to just automatically convert `[lex.literal]` into a link to e.g. https://timsong-cpp.github.io/cppwp/n4659/lex.literal. 

cheers,
Christian

[*] With `pdfinfo` installed you can get a list of named destinations from a PDF using the following command:

    pdfinfo -dests ~/Downloads/n4659.pdf

The N4659 PDF contains quite a few named destinations, including e.g. tables, listings and footnotes, but they all seem to be hard coded numbers like http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf#nameddest=table.5.9

**Comment by knatten** [comment]
Good idea! I think the best option would be to automatically convert references to links to timsong-cpp. So for instance `[basic.fundamental]§6.9.1¶1` will turn into `<a href="https://timsong-cpp.github.io/cppwp/n4659/basic.fundamental#1">[basic.fundamental]§6.9.1¶1</a>`.

We already have a function that does some custom processing on standard references, so this could be extended to insert links: https://github.com/knatten/cppquiz/blob/master/cppquiz/quiz/templatetags/quiz_extras.py#L10-L15 This is a pure python function, so it can be done by anyone with basic Python knowledge, you don't need to know Django or any other libraries. It's also covered by tests here: https://github.com/knatten/cppquiz/blob/master/cppquiz/quiz/templatetags/quiz_extras_test.py

Adding the `good first issue` label in case someone wants to have a go before I get around to it.

**Comment by wrazik** [comment]
I can take it! Can you help with adding to local instance some element that contains a link to the standard? Default questions contain only "Because `nb`".

**Comment by knatten** [comment]
Cool, thanks! The default questions created by `manage.py create_questions` now contain references to the standard: https://github.com/knatten/cppquiz/pull/154

**Comment by wrazik** [comment]
Thanks! I have some working version(https://github.com/wrazik/cppquiz/commit/8d4a35ed36f644d50735bc21ce7d1e1fc6cdccc9), but failing tests showed that sometimes there is no paragraph name, e.g:
```
    def test_doesnt_include_too_much(self):
        self.assertEqual(u'<em>§3.4¶1</em>.', standard_ref(u'§3.4¶1.'))
```
I don't have better idea than some static map that will translate paragraph number to name. Are you ok with such solution?

**Comment by knatten** [comment]
My idea was to only add links when there are paragraph names in the explanation. If we only have numbers, just don't add the link. Then I can go over and add names when I have time. 

Trying to maintain a map from paragraph numbers to names seems like a big task, which will also lead to more work in the future when we move to C++20.

**Comment by knatten** [comment]
Fixed by https://github.com/knatten/cppquiz/pull/155
