### ISSUE TITLE
Incorrectly linked paragraphs

### ISSUE THREAD

**Issue by wrazik** [knatten/cppquiz#156]
Some paragraphs are incorrectly linked:
http://cppquiz.org/quiz/question/188?result=UD&answer=&did_answer=Answer

in example, this paragraph:
```
[lex.string]§5.13.5¶16:
```
is linked to https://timsong-cpp.github.io/cppwp/n4659/lex.string#1 instead of https://timsong-cpp.github.io/cppwp/n4659/lex.string#16

**Comment by knatten** [comment]
Thanks for reporting! Do you have time to fix this?

**Comment by vsklamm** [comment]
There are some different problems with current regex:
1. Regex matches more than necessary in questions [_188_ ](http://cppquiz.org/quiz/question/188?result=UD&answer=&did_answer=Answer), [_32_](http://cppquiz.org/quiz/question/32?result=OK&answer=abbc&did_answer=Answer), [_193_](http://cppquiz.org/quiz/question/193?result=OK&answer=1&did_answer=Answer):
For example:
https://regex101.com/r/2v65Xb/3
https://regex101.com/r/ntygsy/1
2. Not match some cases in [_184_](http://cppquiz.org/quiz/question/184?result=OK&answer=d&did_answer=Answer) and maybe others
3. The extra brace under italic font in [_11_](http://cppquiz.org/quiz/question/38?result=OK&answer=11&did_answer=Answer) and many others

This fix for [1] and [2] works fine for me: https://regex101.com/r/ntygsy/5
