### ISSUE TITLE
Goofy implementation confuses the question

### ISSUE THREAD

**Issue by LowellBoggs** [knatten/cppquiz#161]
http://cppquiz.org/quiz/giveup/190

The constructor for A looks to be creating a problem.  Parameter i to the constructor should hide the class member named i -- or it looks like it should -- and would have on older compilers.   Languages are very complicated and throwing in seeming confusions like this is unnecessary to the point of the question -- which was about the bool conversions.

Personally, I couldn't see past the potential compile error to see any thing else in the question.

Even if this not a compile error, and I am just wrong about the c++17 compiler's behavior, it confuses the question to anyone who is paying attention to the text.  

Why not give the class member variable a different name, like m_i, so that this unnecessary confusion goes away.

And really, do you want people writing code where name hiding subtleties must be thought through?

**Comment by knatten** [comment]
I agree, having the member named the same as the parameter is confusing, even if it's legal C++. Unfortunately I didn't catch this when I reviewed this submission, but I've updated the question now to use `m_i` for the member as you suggested. Thanks for reporting!

Just since I'm curious: I don't think I've ever worked with a C++ compiler where this is illegal, but you have probably worked with C++ for longer than I have. Do you remember roughly when this became legal?

As for your question "do you want people writing code where name hiding subtleties must be thought through": No I don't. And I should warn here that no code on CppQuiz should be regarded as recommendations on code style, indeed a lot of it is intentionally obscure examples which should be avoided in production code.

**Comment by LowellBoggs** [comment]
Thanks, I am not positive about the compiler error, but I have had variables initialized to themselves - resulting in debug confusions. I may be confusing one pain for another. I have been with c++ since 1997 and there is so much suffering from different composers on different platforms that I get confused. Thanks for listening. Lowell Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Anders Schau Knatten <notifications@github.com> Date: 7/29/19  7:27 AM  (GMT-06:00) To: knatten/cppquiz <cppquiz@noreply.github.com> Cc: LowellBoggs <lboggs@mail.bordoon.com>, Author <author@noreply.github.com> Subject: Re: [knatten/cppquiz] Goofy implementation confuses the question (#161) I agree, having the member named the same as the parameter is confusing, even if it's legal C++. Unfortunately I didn't catch this when I reviewed this submission, but I've updated the question now to use m_i for the member as you suggested. Thanks for reporting!
Just since I'm curious: I don't think I've ever worked with a C++ compiler where this is illegal, but you have probably worked with C++ for longer than I have. Do you remember roughly when this became legal?
As for your question "do you want people writing code where name hiding subtleties must be thought through": No I don't. And I should warn here that no code on CppQuiz should be regarded as recommendations on code style, indeed a lot of it is intentionally obscure examples which should be avoided in production code.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/knatten/cppquiz/issues/161?email_source=notifications\u0026email_token=AAGT7QU2GORCMQTLNQ636VLQB3O2XA5CNFSM4IHNFAAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3ARISQ#issuecomment-515970122",
"url": "https://github.com/knatten/cppquiz/issues/161?email_source=notifications\u0026email_token=AAGT7QU2GORCMQTLNQ636VLQB3O2XA5CNFSM4IHNFAAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3ARISQ#issuecomment-515970122",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by knatten** [comment]
Cool, that's roughly twice as long as me. Thanks for the report!
