### ISSUE TITLE
Question #10 is missing from sequence

### ISSUE THREAD

**Issue by mlilia** [knatten/cppquiz#163]
I'm doing the exercises one by one, starting from #1 (and love them so far!).
When I tried to move to the next question (#10), the page with the following message came up:
`It seems that std::find(pages.begin(), pages.end(), the_page_you_are_looking_for) == pages.end()`

**Comment by knatten** [comment]
Thanks for reporting! Unfortunately that number is just a question ID, it has no semantic meaning as "the tenth question". Questions are assigned an ID when they are created, but some are later removed, some are published after questions with higher IDs etc. So the question ID can unfortunately not be used to iterate through all the questions like that.

**Comment by mlilia** [comment]
I see. Then how can I keep track of the exercises I've completed? Seems there's no account support (yet).

**Comment by knatten** [comment]
There's no convenient way to do that. We do however expose a json dump of all our published questions at http://cppquiz.org/static/published.json.
You could then use a scripting language to pick out the IDs from that dump.

I just pasted it into https://jsonformatter.curiousconcept.com/ now, downloaded it, and ran it through 
```
grep '"id":' data.json | sed -e 's_"id":_http://cppquiz.org/quiz/question_' -e 's/,//'
```

Here's the result:

 http://cppquiz.org/quiz/question135
 http://cppquiz.org/quiz/question12
 http://cppquiz.org/quiz/question205
 http://cppquiz.org/quiz/question25
 http://cppquiz.org/quiz/question124
 http://cppquiz.org/quiz/question195
 http://cppquiz.org/quiz/question153
 http://cppquiz.org/quiz/question191
 http://cppquiz.org/quiz/question157
 http://cppquiz.org/quiz/question233
 http://cppquiz.org/quiz/question133
 http://cppquiz.org/quiz/question38
 http://cppquiz.org/quiz/question3
 http://cppquiz.org/quiz/question17
 http://cppquiz.org/quiz/question222
 http://cppquiz.org/quiz/question29
 http://cppquiz.org/quiz/question120
 http://cppquiz.org/quiz/question158
 http://cppquiz.org/quiz/question35
 http://cppquiz.org/quiz/question145
 http://cppquiz.org/quiz/question206
 http://cppquiz.org/quiz/question129
 http://cppquiz.org/quiz/question4
 http://cppquiz.org/quiz/question15
 http://cppquiz.org/quiz/question140
 http://cppquiz.org/quiz/question132
 http://cppquiz.org/quiz/question121
 http://cppquiz.org/quiz/question217
 http://cppquiz.org/quiz/question192
 http://cppquiz.org/quiz/question7
 http://cppquiz.org/quiz/question252
 http://cppquiz.org/quiz/question114
 http://cppquiz.org/quiz/question161
 http://cppquiz.org/quiz/question162
 http://cppquiz.org/quiz/question160
 http://cppquiz.org/quiz/question37
 http://cppquiz.org/quiz/question130
 http://cppquiz.org/quiz/question188
 http://cppquiz.org/quiz/question113
 http://cppquiz.org/quiz/question6
 http://cppquiz.org/quiz/question151
 http://cppquiz.org/quiz/question5
 http://cppquiz.org/quiz/question265
 http://cppquiz.org/quiz/question131
 http://cppquiz.org/quiz/question163
 http://cppquiz.org/quiz/question118
 http://cppquiz.org/quiz/question44
 http://cppquiz.org/quiz/question26
 http://cppquiz.org/quiz/question9
 http://cppquiz.org/quiz/question41
 http://cppquiz.org/quiz/question16
 http://cppquiz.org/quiz/question147
 http://cppquiz.org/quiz/question236
 http://cppquiz.org/quiz/question30
 http://cppquiz.org/quiz/question31
 http://cppquiz.org/quiz/question174
 http://cppquiz.org/quiz/question198
 http://cppquiz.org/quiz/question186
 http://cppquiz.org/quiz/question122
 http://cppquiz.org/quiz/question148
 http://cppquiz.org/quiz/question228
 http://cppquiz.org/quiz/question105
 http://cppquiz.org/quiz/question115
 http://cppquiz.org/quiz/question119
 http://cppquiz.org/quiz/question219
 http://cppquiz.org/quiz/question49
 http://cppquiz.org/quiz/question52
 http://cppquiz.org/quiz/question227
 http://cppquiz.org/quiz/question152
 http://cppquiz.org/quiz/question24
 http://cppquiz.org/quiz/question2
 http://cppquiz.org/quiz/question159
 http://cppquiz.org/quiz/question250
 http://cppquiz.org/quiz/question8
 http://cppquiz.org/quiz/question111
 http://cppquiz.org/quiz/question178
 http://cppquiz.org/quiz/question248
 http://cppquiz.org/quiz/question13
 http://cppquiz.org/quiz/question107
 http://cppquiz.org/quiz/question197
 http://cppquiz.org/quiz/question189
 http://cppquiz.org/quiz/question144
 http://cppquiz.org/quiz/question220
 http://cppquiz.org/quiz/question1
 http://cppquiz.org/quiz/question230
 http://cppquiz.org/quiz/question11
 http://cppquiz.org/quiz/question18
 http://cppquiz.org/quiz/question27
 http://cppquiz.org/quiz/question28
 http://cppquiz.org/quiz/question224
 http://cppquiz.org/quiz/question112
 http://cppquiz.org/quiz/question185
 http://cppquiz.org/quiz/question32
 http://cppquiz.org/quiz/question109
 http://cppquiz.org/quiz/question208
 http://cppquiz.org/quiz/question225
 http://cppquiz.org/quiz/question193
 http://cppquiz.org/quiz/question125
 http://cppquiz.org/quiz/question177
 http://cppquiz.org/quiz/question229
 http://cppquiz.org/quiz/question196
 http://cppquiz.org/quiz/question106
 http://cppquiz.org/quiz/question184
 http://cppquiz.org/quiz/question42
 http://cppquiz.org/quiz/question261
 http://cppquiz.org/quiz/question231
 http://cppquiz.org/quiz/question48
 http://cppquiz.org/quiz/question33
 http://cppquiz.org/quiz/question126
 http://cppquiz.org/quiz/question187
 http://cppquiz.org/quiz/question254
 http://cppquiz.org/quiz/question116
 http://cppquiz.org/quiz/question226
 http://cppquiz.org/quiz/question190
 http://cppquiz.org/quiz/question127
 http://cppquiz.org/quiz/question249
 http://cppquiz.org/quiz/question14
 http://cppquiz.org/quiz/question259
