### ISSUE TITLE
Add link to CppInsights in the answer

### ISSUE THREAD

**Issue by knatten** [knatten/cppquiz#164]
Just talked to @andreasfertig about this at NDC TechTown. C++ Insights has an api where you can base64 encode a program and pass it in the url. Display this link both if the user got it right/wrong, but not until they have answered.

@knatten to talk to @andreasfertig about the details about how to do this, he mentioned having a python snippet we could use.

(This is similar to #128)

**Comment by andreasfertig** [comment]
Hello @knatten,

great to hear that you like to use C++ Insights for the quiz. Here is a sample in Python which does generate a valid link:

```python
#! /usr/bin/env python
import base64

def cppinsightsLink(code, std='2a', options=''):
    # currently 20 is not a thing
    if '20' == std:
        print('Replacing 20 by 2a')
        std = '2a'

    # per default use latest standard
    if '' == std:
        std = '2a'

    std = 'cpp' + std

    if options:
        options += ',' + std
    else:
        options = std

    return('https://cppinsights.io/lnk?code=%s&insightsOptions=%s&rev=1.0' %(base64.b64encode(code).decode('utf-8'), options))

def main():
    print(cppinsightsLink('#include <cstdio>\n\nint main() {\n  printf("Hello, CppQuiz!\\n");\n}', '11', 'alt-syntax-for'))

main()
```

It is also possible to set some of the C++ Insights options which you can finde [here](https://github.com/andreasfertig/cppinsights-web/blob/0d03e0d0b45510bb04a4217fb85a5a96f31716c0/app/__init__.py#L110). I will probably add this to the readme of the C++ Insights Web repo.

Let me know, if that helps you.

Andreas

**Comment by knatten** [comment]
Thanks a lot! Trying this out on the [cpp-insights branch](https://github.com/knatten/cppquiz/tree/cpp-insights) now. I deployed it to beta.cppquiz.org to test it.

Here's how it looks when you get it right: http://beta.cppquiz.org/quiz/question/1?result=OK&answer=1&did_answer=Answer 

And when you give up: http://beta.cppquiz.org/quiz/giveup/1

The feature works at least, but I haven't really thought much about how/where to display the link yet. Will get back to that next week.

**Comment by knatten** [comment]
@andreasfertig I updated the design a bit, and stole your logo! :) Is it ok if I use it like this? And I'm just hotlinking it for now, can I make a local copy of it?

**Comment by andreasfertig** [comment]
Hello @knatten,

first of all, yes you can use the logo. Feel free to make a local copy.

My personal opinion is, that I'm not sure about the logo and/or the arrangement. For me it hangs there a bit without a clear binding to what it means or where it belongs to. Plus to fit into the space it is small and hard to see? I recognize it, not sure if other does. Maybe others have a different view.

Andreas

**Comment by knatten** [comment]
Yeah, as you can probably tell from the site in general, I'm not good at design. Hopefully someone [on Twitter can help](https://twitter.com/CppQuiz/status/1171861080769007618).

**Comment by knatten** [comment]
I added a link to Compiler Explorer as well. And I didn't like how the icons looked, so I just removed them. I think [it looks good now](http://beta.cppquiz.org/quiz/question/1?result=OK&answer=1&did_answer=Answer):

![Screenshot from 2019-10-14 16-21-49](https://user-images.githubusercontent.com/727543/66758545-c2165e00-ee9e-11e9-82d0-8b991896b9f0.png)
