### ISSUE TITLE
Some little typos in the links to standard

### ISSUE THREAD

**Issue by vsklamm** [knatten/cppquiz#175]
1. `[over.match.best]16.3.3¶1` without `§`, so it does not match the regex
http://cppquiz.org/quiz/giveup/113
There are no more such typos, I checked
2. `§27.5.3.1.4[ios::openmode]` -> [_[ios::openmode]§27.5.3.1.4_](https://timsong-cpp.github.io/cppwp/n4659/ios::openmode) or maybe it doesn't matter
http://cppquiz.org/quiz/giveup/261
Found this while adding "links to standard" feature to the android app

**Comment by knatten** [comment]
Thanks for reporting! I've fixed the links, but it turns out we're missing a feature: #176
