### ISSUE TITLE
Check answer for question #228

### ISSUE THREAD

**Issue by lukaszrachwalski** [knatten/cppquiz#177]
I'm not sure if the answer for the question #228 - http://cppquiz.org/quiz/question/228 is clear enough.

The correct answer for the question: "what is the output of this program" is: "The program is guaranteed to output: "empty text box" - program compiles (in ill formed) and produces no output.

You suggest answer: "The program has a compilation error" which is not true. When someone tries to compile it receives no error and no warning.

I understand the explanation, but I suggest changing the answer adding the message where you can point the details about ill-formed of the program.

**Comment by knatten** [comment]
The alternatives for each question are:
- Guaranteed to output something
- Compilation error
- Unspecified / implementation defined
- Undefined behavior

There's however another category of errors, "ill-formed, no diagnostic required", which is the case for this question. I'm not too keen on adding yet another category in that dropdown, but maybe we should use the "undefined behavior" category for these cases.

After all [intro.complicance](https://timsong-cpp.github.io/cppwp/n4659/intro.compliance#2.3) says about "no diagnostic required":
> If a program contains a violation of a rule for which no diagnostic is required, this International Standard places no requirement on implementations with respect to that program.

Which is very similar to what [intro.execution](https://timsong-cpp.github.io/cppwp/n4659/intro.execution#5) says about undefined behavior:
> if any such execution contains an undefined operation, this International Standard places no requirement on the implementation executing that program with that input

It might be a good idea to add a ❔next to the dropdown explaining the alternatives.

**Comment by Rakete1111** [comment]
Yeah, ill-formed NDR is basically unconditional UB for the whole program.

So I agree, UB would be the better option here, especially since the major compilers appear to accept it.

**Comment by knatten** [comment]
I've changed the correct answer to UB now, and updated the explanation accordingly:

http://cppquiz.org/quiz/question/228?result=UD&answer=&did_answer=Answer

**Comment by knatten** [comment]
Thanks a lot for reporting, @lukaszrachwalski !
