### ISSUE TITLE
Make content available

### ISSUE THREAD

**Issue by gabyx** [knatten/cppquiz#182]
Is there away to make the content on cppquiz.com availabe somehow?

Would be cool to be able to have the questions and answer as well in this repositories (e.g. as markdown documents) such that we can provide PRs and Corrections if needed. Also to search through questions with keywords.

**Comment by knatten** [comment]
That's a good idea, which I've been thinking about. It would be quite a bit of work though, as everything is now in a database with a nice auto generated admin backend from Django's ORM. Having everything in a database also makes it very easy to link meta data and statistics to questions. I don't see a way around keeping a database, so I'd have to either set up some kind of sync between the questions in the database and the repo, or find some way of having all the questions in the repo. In the former case I'd have to hand code a new admin backend, or loose the backend entirely for questions.

So in either case it's going to be more work than I have time for in the foreseeable future.

**Comment by knatten** [comment]
If it's of any help, I have a json dump of all published questions. You might be able to use that to search through questions at least: http://cppquiz.org/static/published.json

**Comment by gabyx** [comment]
Ah nice!

**Comment by gabyx** [comment]
What if you would have a simple update script which just updates the json -> Database. And the json would be checkin in Git :-)? So the json is only the Raw Source (no meta data) and you would only make changes through the json to add new questions :-)?

**Comment by knatten** [comment]
Editing one large json would be a pretty horrible experience for updating the questions imo. At least compared to the web admin interface we have today where it's simpel to make edits and see them live on the site. So we're going to need something that syncs both ways, or at least something that makes it very simple to edit one question at a time locally, with a local preview and super easy way of merging it back to the db.

**Comment by knatten** [comment]
I'm making a pass cleaning up old issues. Closing this one as I'm not going to do it.
