### ISSUE TITLE
Minor fixes in the 31th question explanation

### ISSUE THREAD

**Issue by Tocic** [knatten/cppquiz#185]
In the sentence _"This could be interpreted as **a a variable definition** (which was the intention of the programmer in this example), or as **a definition of a function y**, returning an object of type Y, taking a function (with no arguments, returning an object of type X) as its argument."_ of [this question](http://cppquiz.org/quiz/question/31) explanation please fix the highlighted fragments as follows:

- _"a a variable definition"_ -> _"a variable definition"_
- _"a definition of a function y"_ -> _"a declaration of a function y"_

**Comment by knatten** [comment]
Thank you so much for taking the time to report this! I've fixed it now.
