### ISSUE TITLE
Give_up link returns 404, when >0 attempts left

### ISSUE THREAD

**Issue by knatten** [knatten/cppquiz#199]
Originally reported by @vsklamm in #197

**Comment by knatten** [comment]
@vsklamm When there are more than 0 attempts left, you're not supposed to even be shown that link. Can you elaborate a bit on the use case here, what exactly are you doing, what is happening, and what would you expect to happen instead?

**Comment by vsklamm** [comment]
Maybe I used to android app behavior: show the message that user should answer 3 times first. Strange but now it works fine: nothing happens when I click on that link. So you can close this issue.
