### ISSUE TITLE
Another_question link always forwards to question 163

### ISSUE THREAD

**Issue by knatten** [knatten/cppquiz#200]
Originally reported by @vsklamm in #197

**Comment by knatten** [comment]
@vsklamm I can't reproduce this. What I do to try to reproduce:
- Go to https://cppquiz.org/
- I end up at for instance https://cppquiz.org/quiz/question/4
- I click in the "another question" link in "Problems? View a hint or try another question."
- I end up at an arbitrary question which is not 163
- I keep clicking that link and end up at a new question every time

Come to think of it, could it be that you've answered all the questions on the site? What does the "You've answered N of 133 questions correctly." text at the top of the site say?

**Comment by vsklamm** [comment]
Can reproduce only in desktop Google Chrome (mobile and Edge work fine)
https://youtu.be/hFeziWX5QTM

**Comment by knatten** [comment]
Just a hunch, maybe cache behaviour has changed after we switched webhosts. That link is supposed to just take you to /, which is supposed to redirect you to a random question. Maybe / is cached in your browser to redirect you to https://cppquiz.org/quiz/question/163? Could you try to turn off / delete the cache and try again a few times and see what happens? Do you then get a new question you're always redirected to?

**Comment by vsklamm** [comment]
I tried to clear the cache but forgot about AdBlock (shame). Turned off, all is ok now.

**Comment by knatten** [comment]
So just clearing the cache didn't help, but clearing the cache and also turning off AdBlock did help? I worry that there might be an actual problem here that might affect other users too, and think it might be cache related. But I'm not able to reproduce it myself. Do you have time to try to help reproduce it so that we can test a possible fix? No hurry.

**Comment by vsklamm** [comment]
I checked out _AdBlock_, _Adblock Plus_, _Fair AdBlocker_, _Ghostery_ and _uBlock Origin_ in Edge and Chrome. The problem only occurs with _Ghostery_ and _uBlock Origin_ when enabled. I haven't found any information about caching redirects for these ad blockers. Perhaps there is a setting that disables this, but in any case, it is easier for the user to disable the ad blocker for the site. Maybe just adding a message to disable adblocker, if the user has one, will solve the problem?

Clearing the cache is not necessary, because the problem is solved by simply disabling the ad blocker.

I'm using Chrome with uBlock Origin

**Comment by knatten** [comment]
I'd prefer if I could just fix it so it works for everyone, and since I don't run any ads on the site I'd also prefer to not nag people about disabling ad blockers. It _should_ just work, if we can make it to.

I tried to add some extra headers on https://beta.cppquiz.org now to disable any client side caching. Can you see if you're able to reproduce the issue there? (https://cppquiz.org still runs without the extra headers in case you want to compare.)

**Comment by vsklamm** [comment]
It works on beta.cppquiz! Tested with Ghostery and uBlock Origin in Edge and Chrome.

**Comment by knatten** [comment]
Haha, that's so weird that a few (and only a few) ad blockers change the cache behaviour of the browser! Anyway, I think the new behaviour is better in any case. I've added a decorator that disables client side cache for these urls, see #207

**Comment by knatten** [comment]
This is now merged and deployed to the main site.
