### ISSUE TITLE
https://cppquiz.org/quiz/question/10 is 404

### ISSUE THREAD

**Issue by XXXDDD** [knatten/cppquiz#208]
As described in the title.

**Comment by knatten** [comment]
There is no question 10, so the 404 is correct. How did you get to that link, did you just try out different question numbers, or did you end up there from a link on the site itself?

**Comment by XXXDDD** [comment]
Thank you for the reply.
Was manully changing the url to get the next quiz. Now I get the idea, this is as designed.

**Comment by knatten** [comment]
Glad we figured it out! :)
