### ISSUE TITLE
Question #178 is incorrect

### ISSUE THREAD

**Issue by Ryan-Price** [knatten/cppquiz#209]
Couldn't figure out the answer to #178, so tried to compile it.

#include <iostream>
int main(){
        int a = 5,b = 2;
        std::cout << a+++++b;
}

sandbox/sandbox.cpp: In function ‘int main()’:
sandbox/sandbox.cpp:6:18: error: lvalue required as increment operand
  std::cout << a+++++b;
                             ^~

**Comment by knatten** [comment]
It looks like you're reporting that the program has a compilation error? That's also the correct answer [on the site](https://cppquiz.org/quiz/question/178), if you select "The program has a compilation error" as your answer in the dropdown, you have answered correctly. So as far as I can understand, everything is as it should?

**Comment by Ryan-Price** [comment]
I thought I tried that, must of mis-clicked when I tried to submit that answer. My bad

**Comment by knatten** [comment]
No worries! Don't hesitate to make issues if you suspect something's wrong.
