### ISSUE TITLE
Is question 225 correct?

### ISSUE THREAD

**Issue by BenjaminNavarro** [knatten/cppquiz#230]
I might be missing something but to me `std::cout` is a global object and `object` is global one as well. The construction of the second depends on the first one being initialized but the order of initialization is unspecified, so this is UB to me.

**Comment by knatten** [comment]
Very good question! You're of course right that the order of initialisation of global objects is unspecified. However, two globals in the same translation unit are initialised in the order of declaration. And [iostream.objects.overview/1](https://timsong-cpp.github.io/cppwp/n4861/iostream.objects.overview#3) says:

> The results of including `<iostream>` in a translation unit shall be as if `<iostream>` defined an instance of `ios_­base​::​Init` with static storage duration.

As far as I understand, this is the mechanism the standard uses to make sure it's safe to use `cout` / `cerr` during global initialisation.

**Comment by BenjaminNavarro** [comment]
Ok I see, I guess it makes sense and probably relied at some point on it without knowing it.

Thanks for the clarification

**Comment by knatten** [comment]
> Ok I see, I guess it makes sense and probably relied at some point on it without knowing it.

Yeah me too! There's probably a lot of stuff like this to be found around the standard, things we luckily don't have to think about in regular use of the language.
