### ISSUE TITLE
Question 284 seems to be broken

### ISSUE THREAD

**Issue by pppout** [knatten/cppquiz#235]
Both C++ Insights and Compiler Explorer fails to compile.
![2021-06-12-172407_929x254_scrot](https://user-images.githubusercontent.com/25171686/121770237-28d3a980-cba3-11eb-9627-b4fd9b9d17d5.png)
Copying the code gives:
```
#include <iostream>
#include <string>

auto main() -> int {
  std::string out{"Hello world"};
  std::cout << (out[out.size()] == '');
}
```
While the answer says 1 is printed.

**Comment by michael-kenzel** [comment]
Was just going to report the same issue. The problem would seem to be an incorrectly escaped character somewhere. If you check the source code of the website, there's an actual zero byte inside the character literal, which is simply not rendered by the browser. I assume it was supposed to be `'\0'` (which would be consistent with the "correct" answer) but that `\0` got turned into a literal null character somewhere along the way…

**Comment by knatten** [comment]
Thanks for reporting! You're right, there used to be a `\0` there which has somehow been converted into an actual null character. This probably happened when I migrated the site from Webfaction to Dreamhost last year and had some issues with the database migration. Anyway, it's fixed now.
