### ISSUE TITLE
Quiz page gets cached

### ISSUE THREAD

**Issue by sth** [knatten/cppquiz#236]
The same URL is used to display all the questions in a quiz, for example `https://cppquiz.org/q/lgz0t`. This URL allows caching (`max-age=600`), which can lead to new questions not showing up, since the browser might re-display the old cached HTML containing the previous question. This does happen in Firefox.

The easiest fix would probably be to disable caching for this URL by adding `@never_cache` to the [`quiz()` function][1].

 [1]: https://github.com/knatten/cppquiz/blob/3062e903299d229a3b03b7d7f18e71a6571e5d26/quiz/views.py#L119

**Comment by knatten** [comment]
Thanks for reporting! Fixing this in #237.
