### ISSUE TITLE
Question 188 - Null character

### ISSUE THREAD

**Issue by H-G-Hristov** [knatten/cppquiz#241]
https://cppquiz.org/quiz/question/188
  `a[4] = '';` = this line seems to contain a null character. It's unclear if this is a syntax error or not. Even C++ Insights and Compiler Explorer complain about it. Also for a human reader it would be way more clear to use the escaped version.

**Comment by knatten** [comment]
Thanks for reporting! That null character should have been `\0`, I've fixed it now.
