### ISSUE TITLE
Confusing type in 158 answer

### ISSUE THREAD

**Issue by LaicepS** [knatten/cppquiz#242]
In question 158, in the answer text block, the last paragraph reads:

`So this code before C++11 would output abbbbb, because the call would be equivalent to std::vector<Foo> bar(5,T()).`

I think it would be clearer if the last `T()` was `Foo()`. Thus, it would read : 

`So this code before C++11 would output abbbbb, because the call would be equivalent to std::vector<Foo> bar(5,Foo()).`

**Comment by knatten** [comment]
I agree! Thanks for the suggestion, I've updated the explanation now.
