### ISSUE TITLE
Question #127 does not match actual compiler output

### ISSUE THREAD

**Issue by cdfrey** [knatten/cppquiz#243]
https://cppquiz.org/quiz/giveup/127

It says:

"The program is guaranteed to output: 00100"

When I compile it with gcc 8.3.0 or 11.2.0 I get 01000.

I don't understand the issue well enough to know what causes the discrepancy.

**Comment by vsklamm** [comment]
@cdfrey https://github.com/knatten/cppquiz/issues?q=is%3Aissue+is%3Aclosed+127

**Comment by knatten** [comment]
Compiler bug, see https://github.com/knatten/cppquiz/issues/96

**Comment by cdfrey** [comment]
Thank you.  Apologies for not searching first.

I have run into a previous question on cppquiz that pointed out that there was an open compiler bug.  Would it make sense to update the test in question 127 to reference the GCC bug as well?

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66672

**Comment by knatten** [comment]
Good idea! I've updated the explanation now. And don't worry about the duplicate issue, it's better to report once too often than once too seldom.
