### ISSUE TITLE
Question 48

### ISSUE THREAD

**Issue by ProphetUnckleJoe** [knatten/cppquiz#252]
https://cppquiz.org/quiz/question/48. Your answer is not correspond result from godbolt.org. Could you please check?
Related https://en.cppreference.com/w/cpp/language/attributes/nodiscard

**Comment by knatten** [comment]
I checked now, and on godbolt I get `z` on both gcc, clang and msvc: https://godbolt.org/z/xoGTa9sqT. What do you get? Do you have a link I can check out?

**Comment by ProphetUnckleJoe** [comment]
You can use link for godbolt.org from answer explanation https://cppquiz.org/quiz/question/48?result=OK&answer=z&did_answer=Answer

**Comment by knatten** [comment]
Yeah that's just a linker error, since gcc needs a `-lphread` argument. If you provide that, it prints `z`.

**Comment by ProphetUnckleJoe** [comment]
Thanks!
