### ISSUE TITLE
Explanation of the answer to the question #219 

### ISSUE THREAD

**Issue by raavimohindar** [knatten/cppquiz#254]
"So in the case of n2, each time we pass 0.5, it gets truncated to 0, and the sum is (0 + (1 + (0 + (1)))) == 2."
```
auto n2 = sum(1, 0.5, 1, 0.5);
```

Is it not (1 + (0 + (1 + (0)))) == 2 since the type is deduced as ```int```?

**Comment by knatten** [comment]
Yeah it should be `(1+ (0 + (1+ (0))))`, not `(0 + (1 + (0 + (1))))`. Fixed it now. Thanks for reporting!
