### ISSUE TITLE
Answer to the question #323 

### ISSUE THREAD

**Issue by raavimohindar** [knatten/cppquiz#257]
```
#include <iostream>
#include <stdexcept>

struct A {
    A(char c) : c_(c) {}
    ~A() { std::cout << c_; }
    char c_;
};

struct Y { ~Y() noexcept(false) { throw std::runtime_error(""); } };

A f() {
    try {
        A a('a');
        Y y;
        A b('b');
        return {'c'};
    } catch (...) {
    }
    return {'d'};
}

int main()
{
    f();
}
```
For this program the output is ```bcad```

That said, 

> The objects are destroyed in the reverse order of the completion of their construction. 

So the destruction sequence is ```c```, ```b```, ```a```, 'stack unwinding' and ```d``` 

I use the online compiler [online_c++_compiler](https://www.onlinegdb.com/online_c++_compiler) and it **does not** produce the answer ```bcad```

But,

```
#include <iostream>
#include <stdexcept>

struct A
{
  A (char c) : c_ (c) { }

  ~A () { std::cout << c_ << std::endl; }

  char c_;
};

struct Y
{
  ~Y () noexcept (false)
  {
    throw std::runtime_error ("exception: run-time error");
  }
};

A f ()
{
  try
  {
    A a ('a');
    Y y;
    A b ('b');
    A c ('c');
    return c;
  }
  catch (const std::exception & e)
  {
    std::cout << e.what () << std::endl;
  }
  return {'d'};
}

int main ()
{
  f ();
}
```
This produces 
```c``` 
```b``` 
```a``` 
exception: run-time error 
```d```

Did I miss-understood something?

**Comment by knatten** [comment]
Hi, and thanks for reporting an issue! If you look at [the explanation to the question](https://cppquiz.org/quiz/question/323?result=OK&answer=bcad&did_answer=Answer), there's a note that both gcc, clang and msvc are getting this wrong at the moment. There's also references to the standard for why it should really be bcad, including an example which is more or less identical to this question.

Here's a side-by-side comparison of the latest version of gcc, clang and msvc: https://www.godbolt.org/z/ro1TxPoK3. It's also interesting that if you switch gcc to a slightly older version, such as 11.3, it has a different (but still wrong) behaviour than on trunk. It seems it was changed between 11.3 and 12.1.

Does that explain it? Is it ok to close this issue?

**Comment by raavimohindar** [comment]
Yes. My bad and I was bit lazy not to use a real environment. It works as expected ```bacd```

**Comment by knatten** [comment]
> Yes. My bad and I was bit lazy not to use a real environment. It works as expected `bacd`

Thanks for the update! Just to be clear, `bacd` is not the correct result. The correct result would be `bcad`. I assume you're on GCC now, as they are the only compiler I'm aware of which has that particular wrong behaviour.

**Comment by raavimohindar** [comment]
I understood the explanation given to that answer now.

- ```c``` is constructed
- ```b``` is destroyed
- ```y``` is destroyed but causes stack unwinding eventually ```c``` is destroyed
- ```d``` is destroyed finally

Finally its ```bcad```

**Comment by tocic** [comment]
Also there is an SO answer with links to DRs and bug reports: https://stackoverflow.com/a/53168208.
