### ISSUE TITLE
Question #13

### ISSUE THREAD

**Issue by raavimohindar** [knatten/cppquiz#258]
> It is however guaranteed to be initialized before the the use of any function defined in the same translation unit, i.e. before the constructors of b and c are called.

It should read i.e., before the constructors of ```c``` and ```b``` are called? If we go with the order of the declaration inside ```main()```?

> Then, b and c are initialized in order.

This should read ```c``` and ```b``` are initialized in order?

**Comment by knatten** [comment]
Thanks for spotting this! I've fixed the explanation now: https://cppquiz.org/quiz/question/13?preview_key=arega4ga4t
