### ISSUE TITLE
Source of questions

### ISSUE THREAD

**Issue by torarnv** [knatten/cppquiz#259]
The questions (and metadata, hints, answers) don't seem to be maintained in this repository. Is https://github.com/knatten/cppquiz17 the most up to date version of the questions?

**Comment by knatten** [comment]
Hi, the questions are in a database, not in a git repo. That repo was just used to crowdsource porting to C++17, I'll close it now. If it helps, I have a json dump of all the published questions and their meta data at https://cppquiz.org/static/published.json

**Comment by torarnv** [comment]
Ah, thanks for the explanation, and the static dump of questions! :)
