### ISSUE TITLE
URL content mismatch in the 284's explanation

### ISSUE THREAD

**Issue by tocic** [knatten/cppquiz#261]
In [the explanation of the 284th question](https://cppquiz.org/quiz/question/284?result=OK&answer=1&did_answer=Answer) there is a link to [§[string.access]¶1](https://timsong-cpp.github.io/cppwp/n4659/string.access#1), but the text that follows it actually reflects the content of [§[string.access]¶2](https://timsong-cpp.github.io/cppwp/n4659/string.access#2). Since both paragraphs are necessary to understand the answer (because reading only the second paragraph may lead to misunderstanding that `pos >= size()` is OK), I suggest to change this part to something like:

[§[string.access]](https://timsong-cpp.github.io/cppwp/n4659/string.access):

> `const_reference operator[](size_type pos) const;`
> `reference       operator[](size_type pos);`
>
> _Requires_: `pos <= size()`.
> _Returns_: `*(begin() + pos)` if `pos < size()`. Otherwise, returns a reference to an object of type `charT` with value `charT()`, where modifying the object to any value other than `charT()` leads to undefined behavior.

**Comment by knatten** [comment]
Thanks for reporting! I incorporated more of the text in the answer like you suggest. I also tried to just link to string.access, but found that I liked it better to link to string.access¶2, since then the most important part for this question gets highlighted.

What do you think about the updated answer?

**Comment by tocic** [comment]
LGTM, thanks for the quick response.

**Comment by knatten** [comment]
No problem, and thanks for a very good report!
