### ISSUE TITLE
Upgrade Django

### ISSUE THREAD

**Issue by knatten** [knatten/cppquiz#271]
We're on a really old version (2.2) and should upgrade. I haven't been using Django for many years, so would really appreciate some help here.  At the time of writing, 4.1 seems like the best choice, then we can bump to 4.2 when that comes out with hopefully not too much work.

See supported versions at https://www.djangoproject.com/download/#supported-versions

**Comment by TheJadex** [comment]
"pip install --upgrade django" should do the trick :)
