### ISSUE TITLE
cpp quiz question #323 has an incorrect answer

### ISSUE THREAD

**Issue by bscher** [knatten/cppquiz#274]
```
Question
[Question #323](https://cppquiz.org/quiz/question/323) Difficulty: 3

According to the C++17 standard, what is the output of this program?

    
#include <iostream>
#include <stdexcept>

struct A {
    A(char c) : c_(c) {}
    ~A() { std::cout << c_; }
    char c_;
};

struct Y { ~Y() noexcept(false) { throw std::runtime_error(""); } };

A f() {
    try {
        A a('a');
        Y y;
        A b('b');
        return {'c'};
    } catch (...) {
    }
    return {'d'};
}

int main()
{
    f();
}

Answer
The program is guaranteed to output: bcad
```

This is incorrect. The correct output is 'bad'. The godbolt.org link provided after answering the question even outputs 'bad'.
This is because `return {'c'}` constructs an initializer list first (not an object of A, because of return-value-optimization), and then the return is attempted, causing the exception to be thrown and the construction of A('c') is never done, thus 'c' is not printed from any destructor.

Even if the line was `return A('c');`, 'c' would still not be printed out for same reason above.

[Godbolt.org solution](https://godbolt.org/#%7B%22version%22%3A%204%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22row%22%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22codeEditor%22%2C%20%22componentState%22%3A%20%7B%22id%22%3A%201%2C%20%22source%22%3A%20%22%23include%20%3Ciostream%3E%5Cr%5Cn%23include%20%3Cstdexcept%3E%5Cr%5Cn%5Cr%5Cnstruct%20A%20%7B%5Cr%5Cn%20%20%20%20A%28char%20c%29%20%3A%20c_%28c%29%20%7B%7D%5Cr%5Cn%20%20%20%20%7EA%28%29%20%7B%20std%3A%3Acout%20%3C%3C%20c_%3B%20%7D%5Cr%5Cn%20%20%20%20char%20c_%3B%5Cr%5Cn%7D%3B%5Cr%5Cn%5Cr%5Cnstruct%20Y%20%7B%20%7EY%28%29%20noexcept%28false%29%20%7B%20throw%20std%3A%3Aruntime_error%28%5C%22%5C%22%29%3B%20%7D%20%7D%3B%5Cr%5Cn%5Cr%5CnA%20f%28%29%20%7B%5Cr%5Cn%20%20%20%20try%20%7B%5Cr%5Cn%20%20%20%20%20%20%20%20A%20a%28%27a%27%29%3B%5Cr%5Cn%20%20%20%20%20%20%20%20Y%20y%3B%5Cr%5Cn%20%20%20%20%20%20%20%20A%20b%28%27b%27%29%3B%5Cr%5Cn%20%20%20%20%20%20%20%20return%20%7B%27c%27%7D%3B%5Cr%5Cn%20%20%20%20%7D%20catch%20%28...%29%20%7B%5Cr%5Cn%20%20%20%20%7D%5Cr%5Cn%20%20%20%20return%20%7B%27d%27%7D%3B%5Cr%5Cn%7D%5Cr%5Cn%5Cr%5Cnint%20main%28%29%5Cr%5Cn%7B%5Cr%5Cn%20%20%20%20f%28%29%3B%5Cr%5Cn%7D%22%2C%20%22options%22%3A%20%7B%22compileOnChange%22%3A%20true%2C%20%22colouriseAsm%22%3A%20true%7D%7D%7D%2C%20%7B%22type%22%3A%20%22column%22%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22compiler%22%2C%20%22componentState%22%3A%20%7B%22id%22%3A%201%2C%20%22source%22%3A%201%2C%20%22compiler%22%3A%20%22g92%22%2C%20%22filters%22%3A%20%7B%22b%22%3A%201%2C%20%22execute%22%3A%201%2C%20%22intel%22%3A%201%2C%20%22commentOnly%22%3A%201%2C%20%22directives%22%3A%201%7D%2C%20%22options%22%3A%20%22-std%3Dc%2B%2B17%22%7D%7D%2C%20%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22output%22%2C%20%22componentState%22%3A%20%7B%22compiler%22%3A%201%2C%20%22source%22%3A%201%7D%7D%5D%7D%5D%7D%5D%7D)

**Comment by knatten** [comment]
Hi, did you see #257? Can you please read through the feedback in that issue and see if you agree? 

> This is because return {'c'} constructs an initializer list first

Do you mean that it constructs an object of the class template `std::initializer_list`? And that this somehow later gets converted to an object of the struct `A`?

**Comment by tocic** [comment]
@bscher I think this question is fine. It's about C++ standard, not a compiler-specific implementation. In the explanation you can find a link to [the relevant paragraph](https://timsong-cpp.github.io/cppwp/std17/except.ctor#2) and a note about the GCC's inconformance.

Regarding your explanation:

- as of C++17, there's no RVO (but there is a so called NRVO, i.e. there must be [an automatic variable with a name](https://timsong-cpp.github.io/cppwp/std17/class.copy.elision#1.1)), there's a direct construction from a prvalue and a deferred temporary materialization; here the temporary materialization should have happened in `f();`, since it's [a discarded-value expression](https://timsong-cpp.github.io/cppwp/std17/class.temporary#2.6), but it happened earlier in `return {'c'};` because of the exception;
- `return {'c'}` should call the A's constructor according to [this paragraph](https://timsong-cpp.github.io/cppwp/std17/dcl.init.list#3.6) (note that it's different from `std::initializer_list`, if you meant that).

**Comment by bscher** [comment]
Yep, that makes sense... buuut an answer to a question that links to a
demonstration of the "wrong" answer would still be a bug.

Thank you for the the reply, and the insite into the standard about RVO in
this context. Your website was a solid way to warm up for an interview.

-bscher

**Comment by knatten** [comment]
I don't consider that a bug. All the questions on the site link to godbolt, a few of them the compilers actually get wrong, quite a few contain undefined behaviour etc. I still think it's useful to see what happens in the real world. And for this question in particular there's even a note about how the compilers are getting it wrong.

I'm glad you're enjoying the site, and good luck with the interviews! :)
