### ISSUE TITLE
Improved 404 for missing questions

### ISSUE THREAD

**Issue by knatten** [knatten/cppquiz#287]
The question number in the urls correspond to the primary key in the database. Some have been retracted, some were rejected before they were published, some are not published yet, some don't even exist in the database etc. Every now and then someone expects to be able to increment the id in the url as a way to see all the questions on the site. See e.g. #256, #234, #208, #163 

Here's an example for question 10: https://cppquiz.org/quiz/question/10

I suggest we improve the 404 page, so that if one gets to the 404 page due to a question missing (state is not published, or it doesn't exist), we print a better message. In other random missing pages, like https://cppquiz.org/page-that-does-not-exist, we can keep the current one.

Suggestion for message (open to other ideas):
> **Question X is not published.**
>
> If you came here by manually typing in a question ID in the URL, that will not work, as the question IDs are not consecutive. 
>
> Maybe you could [try another question](https://cppquiz.org/)?

**Comment by tocic** [comment]
If #278 is merged, you can get the same error by typing the question's number in the navigation bar. Thus, it makes sense to generalize the message:

```diff
- If you came here by manually typing in a question ID in the URL, that will not work, as the question IDs are not consecutive.
+ If you came here by manually typing in a question ID, that will not work, as the question IDs are not consecutive.
```

Also, maybe use _may_ instead of _will_, since sometimes that does work :)

```diff
- If you came here by manually typing in a question ID, that will not work, as the question IDs are not consecutive.
+ If you came here by manually typing in a question ID, that may not work, as the question IDs are not consecutive.
```
