### ISSUE TITLE
Unexpected bold formatting in the 124's explanation

### ISSUE THREAD

**Issue by tocic** [knatten/cppquiz#288]
There is a formatting problem in [the 124th question's explanation](https://cppquiz.org/quiz/question/124?result=OK&answer=2&did_answer=Answer):

![image](https://user-images.githubusercontent.com/22129543/225054993-3263b862-95ef-4979-bc10-5d73253795f6.png)

`<B>` in `C<B>::f()` is interpreted as an HTML tag.

**Comment by knatten** [comment]
Thanks, fixed. The explanation was just missing some backticks,
