### ISSUE TITLE
Compiler Explorer's link in 339 uses -lpthread instead of -pthread

### ISSUE THREAD

**Issue by tocic** [knatten/cppquiz#289]
[The 339th question's explanation](https://cppquiz.org/quiz/question/339?result=UD&answer=&did_answer=Answer) contains an additional Compiler Explorer link. That link uses `-lpthread` flag which is fine for `gcc`, but produces a warning in `clang`. Consider using `-pthread` instead. See https://stackoverflow.com/q/2391194 for details.

![image](https://user-images.githubusercontent.com/22129543/225274489-92189d44-6eab-4345-a78a-6aaa29554385.png)

**Comment by knatten** [comment]
Thanks for reporting! I'll leave this open until it's possible to execute programs on msvc on CE again. Right now I 'm unable to create a new link that also executes the code on msvc. So let's just live with this warning in the mean time.

**Comment by knatten** [comment]
https://github.com/compiler-explorer/compiler-explorer/issues/4769 is the issue we're waiting for. If someone notices it being closed before I do, feel free to ping me in this thread.

**Comment by knatten** [comment]
MSVC execution is now back on CE! So we can finally fix this now.
