### ISSUE TITLE
Stylistic issues in the code of 144

### ISSUE THREAD

**Issue by tocic** [knatten/cppquiz#290]
There are 2 minor issues in [the 144th question's explanation](https://cppquiz.org/quiz/question/144?result=OK&answer=010&did_answer=Answer):

- the code is not fully indented:

```diff
- for (long int i = -0xffffffff; i ; --i)
+ for (long int i = -0xffffffff; i; --i)
```

```diff
- N[1]=1;
+ N[1] = 1;
```

```diff
- std::cout << N[0] <<N [1] << N[2];
+ std::cout << N[0] << N[1] << N[2];
```

- [the code produces `warning C4127: conditional expression is constant` with `msvc /W4`][1], which will require an exception in #255, so the following patch is useful (also for educational reasons):

```diff
- if ( std::numeric_limits<long int>::digits==63 &&
+ if constexpr ( std::numeric_limits<long int>::digits==63 &&
```

[1]:
https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:6,endLineNumber:8,positionColumn:6,positionLineNumber:8,selectionStartColumn:6,selectionStartLineNumber:8,startColumn:6,startLineNumber:8),source:'%23include+%3Ciostream%3E%0A%23include+%3Climits%3E%0A%0Aint+main()%0A%7B%0A++int+N%5B%5D+%3D+%7B0,0,0%7D%3B%0A%0A++if+(+std::numeric_limits%3Clong+int%3E::digits%3D%3D63+%26%26%0A++++std::numeric_limits%3Cint%3E::digits%3D%3D31+%26%26%0A++++std::numeric_limits%3Cunsigned+int%3E::digits%3D%3D32+)%0A++%7B%0A++++for+(long+int+i+%3D+-0xffffffff%3B+i+%3B+--i)%0A++++%7B%0A++++++N%5Bi%5D+%3D+1%3B%0A++++%7D%0A++%7D%0A++else%0A++%7B++%0A++++N%5B1%5D%3D1%3B%0A++%7D%0A%0A++std::cout+%3C%3C+N%5B0%5D+%3C%3CN+%5B1%5D+%3C%3C+N%5B2%5D%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:vcpp_v19_latest_x64,deviceViewOpen:'1',filters:(b:1,binary:'1',binaryObject:'1',commentOnly:1,demangle:'0',directives:1,execute:1,intel:1,libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'/std:c%2B%2B17+/W4',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x64+msvc+v19.latest+(Editor+%231)',t:'0')),l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x64+msvc+v19.latest+(Compiler+%231)',t:'0')),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

**Comment by knatten** [comment]
Thanks, fixed
