### ISSUE TITLE
CI runs twice on PRs from the same repo

### ISSUE THREAD

**Issue by tocic** [knatten/cppquiz#295]
I've noticed that on your PRs the CI runs twice, since it's considered to be both a `push` and `pull_request` event. PRs from forks are fine.

Compare [#294](https://github.com/knatten/cppquiz/pull/294/checks) and [#291](https://github.com/knatten/cppquiz/pull/291/checks).

Quick searching shows that this line can help:

```
if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
```

**Comment by knatten** [comment]
Do you know if it's possible to avoid duplicating that line in every job? I'd like to avoid complicating things for this, as it isn't really a problem.

**Comment by tocic** [comment]
Unfortunately, I don't have much experience with GitHub actions, so I can't assert the solutions. But I think the following will also work:

```yaml
on:
  push:
    branches: master
  pull_request:
```

**Comment by knatten** [comment]
That will mean branches in this repo don't run until there's a PR, won't it?

**Comment by tocic** [comment]
Yes, pushes to non-master non-PR branches will not trigger the actions.

**Comment by knatten** [comment]
Thanks for reporting, but I don't think this really matters and am not going to spend time on it unless someone knows exactly how to fix it.
