### ISSUE TITLE
Question #231

### ISSUE THREAD

**Issue by jaroslawroszyk** [knatten/cppquiz#311]
```

#include <iostream>
struct override {};
struct Base {
    virtual override f() = 0;
};
struct Derived : Base {
    virtual auto f() -> override **override**{  <- there shouldn't be a second override here
        std::cout << "1";
        return override();
    }
};

int main() {
    Derived().f();
}
```

**Comment by tocic** [comment]
That's not a typo, check out the question's explanation to learn why. In short, the `override` keyword is considered a keyword only in some contexts, and here the first `override` is not a keyword but a class name.

**Comment by knatten** [comment]
Explanation: https://cppquiz.org/quiz/question/231?result=OK&answer=1&did_answer=Answer

**Comment by jaroslawroszyk** [comment]
Sorry my mistake..

**Comment by knatten** [comment]
No problem! I always appreciate when people take the time to report suspected bugs.
