### ISSUE TITLE
Question 323 wrong result

### ISSUE THREAD

**Issue by fifty59nine** [knatten/cppquiz#321]
[Question 323](https://cppquiz.org/quiz/question/323) have answer `bcad`, but should UB.
Result on g++ 13.2.1: `bacd`
Result on clang++ 16.0.6: `bad`

Tested on Fedora 16.0.6

Code of question:
```cpp
#include <iostream>
#include <stdexcept>

struct A {
    A(char c) : c_(c) {}
    ~A() { std::cout << c_; }
    char c_;
};

struct Y { ~Y() noexcept(false) { throw std::runtime_error(""); } };

A f() {
    try {
        A a('a');
        Y y;
        A b('b');
        return {'c'};
    } catch (...) {
    }
    return {'d'};
}

int main()
{
    f();
}
```

**Comment by fifty59nine** [comment]
Duplicate

**Comment by tocic** [comment]
For future readers: see https://github.com/knatten/cppquiz/issues/274 and https://github.com/knatten/cppquiz/issues/257.

(Btw, it's better to "Close as not planned" rather than "Close as completed".)
