### ISSUE TITLE
Confused by Question #147

### ISSUE THREAD

**Issue by nintendoeats** [knatten/cppquiz#324]
What is going on here _indeed_!
The only test seems to be whether we are brave enough to assume that the world is sane, and the code we are looking at is real. Glad to know that stuff in comments doesn't get compiled?

**Comment by tocic** [comment]
Please look at [the compiler link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjEIADspAAOqAqETgwe3r7%2ByanpAiFhkSwxcYl2mA4ZQgRMxARZPn4BldUCtfUERRHRsQm2dQ1NOa1D3aG9pf3xAJS2qF7EyOwc5gDMocjeWCbrbk4KBMSYrHvYJhoAgpdXoQQA1CxMoRCzJvFW1w8P9w%2BqewAIho9hYHgB6cEAdQQTEeeAUDwA7sQBMAHghYpg9gAxXHg24/AHrQFcUGEh5HdAgFCLAh7NwM4lfG7xQEcea0TgAVl4fg4WlIqE4jMs1kpi2WmAeGx4pAImg58wA1iB1vEAHTc/ScSR8xVCzi8BQgDTyxXzOCwGCIWksJJ0WLkShoe2OuLABTMJIKBCoAh8OgEWImiBRPRRUL1ACenDlkeYxGjAHkotoqgruLxXWxBMmGLRY1xSFgol5gG4xLQTVmS5hnkZxALePgTtUAG6YE3FzCqKpeYN6e6YLnF2h4KLEGMeLAG454Fhxjl8AyegBqeEwSOTSUYS5kghEYnYUgP8iUagNujHhmM1ms%2BgnJsg81QSUcAhrAFoqUDTGLLC4eIHi/KEqxAqFe2OJgIIYVAvy8BgvCUdAIMQ5DMHQL92zELxMF4VBO2IYg8CwZ83lsEcMwyFwGHcTxmj0YJJhKMo9BSNIP0yBicmLDiCgYHpWP6Ys2i4zphh4vxRKo9oGAkiZij6OJRPGEZpMGLohOUiR5gUSUVl0nUOF5Uh%2BUFYUOH%2BAAOAA2L9bMkB5gGQZAHggY5EOVWZ3NwQgSBlMx1i4WZeEzLRZk5XVeEXbkzXMgijVsU1zWbS0bQgJA6SSAdnWoWQj3EU9%2BEERQVHUZtSGvUgUSYJIlyikz9UqyzkwHHLHlQKgbPsxznNc9zPIYbz3I8N16GIQLgtC1KIsavVSFi%2BKDUs40UvCpVSFVdUtWM9ZmospKNvS%2BArVtXt%2ByIMgKAgepPWUQwRyEP0kX5OVXQdAwuIesJaGe1BXoND73RQAwjAAfSG5VSGBibwlYVZs1QcbYja4QXre3gLuQK5iE9JLsdqfB%2BV4ErhFEIrpDJsrL0q6qwbvACbHHKJyNfd8Mm/X8SX/KxAOAn8CHQFmgRZ3nxVA8DQKgqdYPg9CULlhCkJQr8knqBHg0m0CFcwr8TgULxaEeHWVb1nDvHwoUiJIsj4HmYhEMcNgABVUE8NmFiWQzVOJn6nox/davqrNGtMhLDQ4bA%2B2QAcAtUOyHKc7Zb0Gx3hp8iBRT5mwHj8q6ppCsKLXmmKQDisyVqSk0zWO0gzsykBsbj67KDuhR/b%2BwPa1huEMk7/7Acq2H%2BnbZAkiScH2y4ABOcGvq7AhwdURyYeRz7YnhtgkpH4g0cHzHAhj3H8Y4LGY6J0IkrJwqTyp2QaYqwVdACBmUHvSxH1Z%2B2hQ5z9OHBFSd%2BTMgIQihE5cESJ0CSC4BoDQEIoEwI0FwBB0CuDWRngRG2pEuw/3Ts7TAbsPY/30t7E8gw/aPS7gDQ%2BwcGrGXDlXKOMcW7/D6iwBQY8HjTxnhqBeRxRof1zvnAKsoZrHVLotcuy0WrV3WiXLa/htRcg4PtSusiz6zU2ioswB1EqaIkaQIiaRnCSCAA%3D%3D) provided in the answer. You can add the `-trigraphs` option to see the difference (it will compile, but the result will be different).

**Comment by nintendoeats** [comment]
That's neat, and I'm happy to know about it, but here's the thought process I went through (which I'd think is the same for most users):

1. I really really hope that this is 1.
2. But it couldn't possibly be 1. I mean, why would they ask?
3. There's this unusual comment, but it's just a comment.
4. Even the syntax highlighter agrees, that's just a comment
5. Well I give up, I'm entering 1.
6. ![image](https://github.com/knatten/cppquiz/assets/6626541/0173bfc1-2a43-4e4d-a23b-4b2725c6280e)
7. So I'm right that this is 1.
8. And I'm right that that was just a comment.
9. So what I have learned was that there used to be a trigraph called `??/`, but I don't know what it does and it's not actually relevant to the question I just answered.

Can you see why, coming at it from that perspective, the question just comes across as very strange?

I think what it comes down to is, if you knew what this trigraph was and what it did then this question is about "did you know this was removed in C++17". But if you don't (which I think is pretty common, given that it was removed), the question is "can you read code", and the answer description says "there's also a thing here which does nothing and is ignored".

Perhaps the solution is to add something like this to the explanation:

> Prior to C++17, the `??/` was parsed by the preprocessor as being equivalent to the character `\`. Thus, the next line with `x = 1;` would have been treated as part of a multiline comment rather than as executable code. Therefore the output would have been `0` in older versions of the standard.
> You can reenable this behavior in GCC using the `-trigraphs` option, or by specifying `-std=c++14`.

**Comment by knatten** [comment]
I suggest we simply un-publish this question. It was created pre-C++17 when trigraphs were still a thing. Then it got ported to C++17 with the rest of the questions on the site, but I think it should have been unpublished instead since it no longer makes much sense. Any objections?

**Comment by knatten** [comment]
The question has now been retracted: https://cppquiz.org/quiz/question/147
