### ISSUE TITLE
English grammar issue in question №15 

### ISSUE THREAD

**Issue by AliAshkaniNia** [knatten/cppquiz#331]
I spotted some small grammatical issues in the answer to question №15: 

- "attempted initialized" should be "attempted to be initialized".
- The phrase "neither b or B::a" should use "nor" instead of "or" to correctly pair with "neither".

I have edited the entire paragraph for better clarity:

Static local variables are initialized the first time control passes through their declaration. The first time `foo()` is called, `b` is attempted to be initialized. Its constructor is called, which first constructs all member variables. This means `A::A()` is called, resulting in the printing of 'a.' However, `A::A()` then throws an exception; consequently, the constructor is aborted, and neither `b` nor `B::a` are actually considered constructed. In the catch block, 'c' is printed, and then `foo()` is called again. Since `b` was never successfully initialized the first time, it tries again, this time succeeding, which leads to 'ab' being printed. When `main()` exits, the static variable `b` is destroyed. This process first calls the destructor, which prints 'B,' and then destroys the member variables, indicated by the printing of 'A'.

**Comment by knatten** [comment]
Hi, and thanks for taking the time to report this! I've updated the explanation now. https://cppquiz.org/quiz/question/15?preview_key=6slm8y7t2d
