### ISSUE TITLE
Question #251 has a potentially unsafe link

### ISSUE THREAD

**Issue by adamvirovecz** [knatten/cppquiz#333]
Hi,
The [question #251](https://cppquiz.org/quiz/question/251) solution includes a link which was flagged by my antivirus. The link is in the footer: "Note: This example is taken from Why Not Specialize Function Templates? by Herb Sutter." and it points to `http://www.gotw.ca/publications/mill17.htm`.

When it was opened I got a detection alert:
*The file [...] has been detected as infected with JS:Trojan.Cryxos.5427. Bitdefender deleted this item, your device is safe.*

It may be a false warning but it's better to be safe.

**Comment by tocic** [comment]
No warnings from my browser or virustotal. But perhaps we can change the link so that it leads to web.archive.org?

**Comment by knatten** [comment]
Changed it to archive.org now.
