### ISSUE TITLE
Adding questions on C-language, as separate chapter

### ISSUE THREAD

**Issue by CODER591** [knatten/cppquiz#335]
What do you think about extending the website scope with questions on C language?

It has few benefits, as
 - Website will attract the C engineers to prepare for interview better.
 - C standard was very stable compared to the C++ (easier to support)
 - C language is much smaller than C++, thus fewer questions will be required to cover all topics.
 
 I can contribute a few questions on C, though without particular references to a standard.
 
 Best regards!

**Comment by knatten** [comment]
That's a cool idea, but I would rather keep the focus on C++. It's the language that I as a maintainer know, and it's a lot of effort to extend the site to support this, to write all the questions, and to maintain all of it.
