### ISSUE TITLE
Question #231 has compilation errors

### ISSUE THREAD

**Issue by WebDancer69** [knatten/cppquiz#354]
Question #231 has compilation errors, but does not accept that as the answer.

<source>:10:25: error: two or more data types in declaration of 'type name'
   10 |     virtual auto f() -> override override{
      |                         ^~~~~~~~
<source>: In function 'int main()':
<source>:17:13: error: invalid cast to abstract class type 'Derived'
   17 |     Derived().f();
      |             ^
<source>:9:8: note:   because the following virtual functions are pure within 'Derived':
    9 | struct Derived : Base {
      |        ^~~~~~~
<source>:6:22: note:     'virtual override Base::f()'
    6 |     virtual override f() = 0;
      |                      ^
ASM generation compiler returned: 1
<source>:10:25: error: two or more data types in declaration of 'type name'
   10 |     virtual auto f() -> override override{
      |                         ^~~~~~~~
<source>: In function 'int main()':
<source>:17:13: error: invalid cast to abstract class type 'Derived'
   17 |     Derived().f();
      |             ^
<source>:9:8: note:   because the following virtual functions are pure within 'Derived':
    9 | struct Derived : Base {
      |        ^~~~~~~
<source>:6:22: note:     'virtual override Base::f()'
    6 |     virtual override f() = 0;
      |                      ^
Execution build compiler returned: 1

**Comment by WebDancer69** [comment]
I used x86-64 gcc (trunk) (currently 15.0.0 20240828 experimental) with Compiler Explorer.

**Comment by tocic** [comment]
Please see #148 and #311.

**Comment by knatten** [comment]
Thanks for reporting! By "has compilation errors", do you mean it fails to compile on a particular compiler (gcc) or that the standard says it should not compile?

If you click the [compiler explorer link in the question](https://godbolt.org/#%7B%22version%22%3A%204%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22row%22%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22codeEditor%22%2C%20%22componentState%22%3A%20%7B%22id%22%3A%201%2C%20%22lang%22%3A%20%22c%2B%2B%22%2C%20%22source%22%3A%20%22%23include%20%3Ciostream%3E%5Cn%5Cnstruct%20override%20%7B%7D%3B%5Cn%5Cnstruct%20Base%20%7B%5Cn%20%20%20%20virtual%20override%20f%28%29%20%3D%200%3B%5Cn%7D%3B%5Cn%5Cnstruct%20Derived%20%3A%20Base%20%7B%5Cn%20%20%20%20virtual%20auto%20f%28%29%20-%3E%20override%20override%7B%5Cn%20%20%20%20%20%20%20%20std%3A%3Acout%20%3C%3C%20%5C%221%5C%22%3B%5Cn%20%20%20%20%20%20%20%20return%20override%28%29%3B%5Cn%20%20%20%20%7D%5Cn%7D%3B%5Cn%5Cnint%20main%28%29%20%7B%5Cn%20%20%20%20Derived%28%29.f%28%29%3B%5Cn%7D%22%2C%20%22options%22%3A%20%7B%22compileOnChange%22%3A%20true%2C%20%22colouriseAsm%22%3A%20true%7D%7D%7D%2C%20%7B%22type%22%3A%20%22column%22%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22compiler%22%2C%20%22componentState%22%3A%20%7B%22id%22%3A%201%2C%20%22source%22%3A%201%2C%20%22filters%22%3A%20%7B%22b%22%3A%201%2C%20%22execute%22%3A%201%2C%20%22intel%22%3A%201%2C%20%22commentOnly%22%3A%201%2C%20%22directives%22%3A%201%7D%2C%20%22compiler%22%3A%20%22gsnapshot%22%2C%20%22options%22%3A%20%22-std%3Dc%2B%2B17%20-Wall%20-Wextra%20-Wno-unused%20-Wunused-value%22%7D%7D%2C%20%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22output%22%2C%20%22componentState%22%3A%20%7B%22compiler%22%3A%201%2C%20%22source%22%3A%201%7D%7D%5D%7D%2C%20%7B%22type%22%3A%20%22column%22%2C%20%22width%22%3A%2025%2C%20%22content%22%3A%20%5B%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22executor%22%2C%20%22componentState%22%3A%20%7B%22id%22%3A%201%2C%20%22source%22%3A%201%2C%20%22compilationPanelShown%22%3A%201%2C%20%22compiler%22%3A%20%22clang_trunk%22%2C%20%22options%22%3A%20%22-std%3Dc%2B%2B17%20-stdlib%3Dlibc%2B%2B%20-Wall%20-Wextra%20-Wno-unused%20-Wno-unused-parameter%20-Wunused-result%20-Wunused-value%22%7D%7D%2C%20%7B%22type%22%3A%20%22component%22%2C%20%22componentName%22%3A%20%22executor%22%2C%20%22componentState%22%3A%20%7B%22id%22%3A%202%2C%20%22source%22%3A%201%2C%20%22compilationPanelShown%22%3A%201%2C%20%22compiler%22%3A%20%22vcpp_v19_latest_x64%22%2C%20%22options%22%3A%20%22/std%3Ac%2B%2B17%20/W4%20/wd4100%20/wd4101%20/wd4189%22%7D%7D%5D%7D%5D%7D%5D%7D), you can see that this compiles fine with clang and msvc. The explanation to the question also explains why this is, in fact, legal C++. I believe this is a bug in gcc, unless you take issue with anything in particular in the explanation to the question. Please re-open if you disagree.

**Comment by WebDancer69** [comment]
I agree, it seems it (still) is a gcc bug.
