### ISSUE TITLE
Quiz 127 does not compile due to the missing of `std`

### ISSUE THREAD

**Issue by sweet2honey** [knatten/cppquiz#368]
https://cppquiz.org/quiz/question/127

The code snippet provided does not compile, nor does the code in Compiler Explorer.

But you do provide a great explanation on the quiz, can't thank you more 😃

**Comment by knatten** [comment]
Oops, thanks for reporting! We just ported all the questions to C++23 and did some cleanup in the process. This one seems to have slipped through the cracks. Fixed now.

**Comment by tocic** [comment]
My bad :cry:, but let's reformat the code like before for readability:
```cpp
#include <iostream>
#include <type_traits>

int main()
{
  int i, &j = i;
  [=]
  {
    std::cout << std::is_same<decltype    ((j)),     int         >::value
              << std::is_same<decltype   (((j))),    int      &  >::value
              << std::is_same<decltype  ((((j)))),   int const&  >::value
              << std::is_same<decltype (((((j))))),  int      && >::value
              << std::is_same<decltype((((((j)))))), int const&& >::value;
  }();
}
```

**Comment by knatten** [comment]
No worries. And yeah that's better formatting, fixed it now.
