### ISSUE TITLE
Explanation of quiz 177

### ISSUE THREAD

**Issue by sweet2honey** [knatten/cppquiz#369]
In the explanation of the quiz, which gives:
> Table 14 in §[basic.fundamental] specifies the **size of signed char as 8**

conflicts with

> So unsigned char is the same size as signed char, which is **at least 8 bits.**

After refering to the standard provided, I suppose the right description should be something like:
> `signed char`'s **minimum width** is 8 bits

**Comment by knatten** [comment]
Thanks! Fixed it now.
