### ISSUE TITLE
Question 127 wrong answer for GCC<=13.3

### ISSUE THREAD

**Issue by verssy** [knatten/cppquiz#375]
https://cppquiz.org/quiz/question/127

tested via [godbolt](https://godbolt.org/) with compile flag `-std=c++23`
GCC<=13.3 lead to answer `01000`
GCC>=14.1 - `00100`

It may be the intended behavior, but not sure

**Comment by knatten** [comment]
This question keeps getting reported as a bug, but it is actually correct. It is explained at the end of [the explanation](https://cppquiz.org/quiz/question/127?preview_key=awrgawta4a). A longer discussion is available in previous issues such as https://github.com/knatten/cppquiz/issues/96.

**Comment by verssy** [comment]
Oh, thank you for explanation!
