### ISSUE TITLE
Quiz 106 is incorrect. Its result is undefined

### ISSUE THREAD

**Issue by RealLitb** [knatten/cppquiz#57]
The spec says "Every program shall contain exactly one definition of every non-inline function or variable that is odr-used in that program; no diagnostic required. ".

Since no diagnostic is required, the program behavior is undefined per 1.4p1 and p2

**Comment by knatten** [comment]
Thanks for the input @RealLitb! It sounds to me like you might be correct. I've contacted the original author of that question to hear his/her opinion.

**Comment by Xazax-hun** [comment]
I agree. The answer and the explanation should be modified.

**Comment by knatten** [comment]
I've updated the result and the explanation now. I also upped the difficulty to "expert".
