### ISSUE TITLE
Question #151 - unspecified != implementation-defined in the Standard

### ISSUE THREAD

**Issue by bogiord** [knatten/cppquiz#61]
The explanation is fine, but I don't think having to choose *is unspecified* as the answer is correct. Of the four available options, *is compilable and deterministic* seems closer to the truth; the problem is that the actual output depends on the implementation, so you can't give one that is "according to the Standard".

For more details, see [1.9p2 and p3]. Basically, *implementation-defined* means documented, deterministic behaviour, while *unspecified* means (potentially) nondeterministic, which clearly doesn't fit the example in the question.

I think an ideal solution would be to have a checkbox that replaces the text box after "and the output is" with the text "implementation-defined". 

Adding *is implementation-defined* as a possible answer is not that good in my opinion, as it would seem to imply that such an example is not *compilable and deterministic*, which is not the case.

**Comment by RealLitb** [comment]
I have always wondered about whether an implementation can define an implementation-defined behavior to be nondeterministic. Does 1.9p2 rule that out? For example, "Physical source file characters are mapped, in an implementation-defined manner, to the basic source character set (introducing new-line characters for end-of-line indicators) if necessary.": Can the mapping from phyiscal characters to basic source characters be non-deterministic as long as this non-determinism is documented?

**Comment by bogiord** [comment]
An interesting point of view, @RealLitb. Here are my thoughts:

*Unspecified* doesn't *require* nondeterminism, it doesn't require that the exact behaviour is not documented, it only allows the implementation to make such choices. In fact, I've encountered examples of behaviour that is *unspecified* in the Standard but clearly documented as deterministic in a particular implementation (especially on the standard library side).

If *implementation-defined* behaviour were allowed to be documented as nondeterministic, what would be the practical difference between the two terms? What's the difference between saying 

> this depends on the implementation, and the implementation is allowed not to specify what it does here 

and 

> this depends on the implementation, and the implementation must document it, but it's allowed to say that it doesn't specify what it does here

?

What would be the point in having two different terms then? The Standard text could just use *unspecified* in all cases, and implementations would still be free to choose the behaviour and how much of it they want to document in each case.

Some additional (but weaker) arguments: 

- [1.9p3] says about unspecified aspects that "These define the nondeterministic aspects of the abstract machine."; it doesn't say that about anything else - it's "*the* nondeterministic aspects", not "some of the..." or something like that. That, to me, implies that this is the only source of nondeterminism in the abstract machine (`std::random_device` notwithstanding - different beast).
- On the other hand, [1.9p2] says about implementation-defined parts that "These constitute the parameters of the abstract machine.", and that they define an instance of the abstract machine. This doesn't sound like something that leaves room for nondeterminism.

So, in my opinion, the answer to your question is "no".

**Comment by RealLitb** [comment]
Yes, I do agree with you. I had the same reasoning about this, but the "what is the difference between unspecified and implementation defined then" argument is new to me and convincing aswell. Thanks.

**Comment by knatten** [comment]
Thanks for an interesting discussion! I was in fact not aware that there was a difference between unspecified and implementation defined behaviour. I've read up a bit on it now, and I think my alternatives "compilable and deterministic" vs. "unspecified" use unfortunate wording. I do not however think it makes sense to differentiate between unspecified and implementation defined in the quiz. The important part is to distinguish these cases from the well defined, and the undefined cases.

What do you think about changing the wording of the alternatives to the following?
- "is compilable and well defined"
- "has a compilation error"
- "is unspecified / implementation defined"
- "is undefined"

**Comment by bogiord** [comment]
I agree with the grouping of *unspecified* and *implementation-defined*, it keeps things simpler.

I'm only-so-very-slightly against having "well defined" in the first alternative, but I've been trying to find some other wording that is concise and communicates the essence... and, so far, failed. The problem is that the categories are supposed to be disjoint, so, if something belongs to the third category, it means it's not compilable or not well defined. Since those are compilable, it means they're not well defined; calling something that's "implementation-defined" "not well defined" is a bit strange in my opinion, but this might be just me going overboard with logic.

I guess what I'm looking for is something concise that says "and the standard specifies that, when run, it produces the following output". Riiight...

Sorry for the ramblings and the nitpicking. Your solution might well be the clearest way to express things.

**Comment by knatten** [comment]
If I wasn't into nitpicking, I wouldn't have created CppQuiz in the first place! ;)

I'm slightly against "well defined" myself, but like you I've failed to come up with something better. But what if we change it to only "compliable", and  then add "guaranteed to be" in the text after the dropwdown? Like this:

![screen shot 2016-03-16 at 18 44 04](https://cloud.githubusercontent.com/assets/727543/13822752/36453778-eba7-11e5-8c5e-84645db11408.png)

**Comment by bogiord** [comment]
If we consider the name of the category to be "is compilable and the output is guaranteed", then that's great. 

If we take the name to be just "is compilable", then that would imply that the Standard doesn't guarantee that any of the others are compilable, which is not true for "unspecified / implementation-defined". In any case, I think this is better, as "well defined" doesn't really help in there.

While we're at it, since the question is "what is the output?", what if we lose the "is compilable" altogether? Something like this:

![cppq](https://cloud.githubusercontent.com/assets/4967002/13831035/65790e2a-ebd9-11e5-9444-9c62fd9ea0dd.png)

The third option makes the whole thing a bit too long.

**Comment by knatten** [comment]
Did basically that now. Thanks for an interesting discussion! :)

**Comment by bogiord** [comment]
It's looking good. Thank you for a great site; I enjoyed every one of those questions.
