### ISSUE TITLE
Question #140

### ISSUE THREAD

**Issue by timsong-cpp** [knatten/cppquiz#65]
Since we are being pedantic here, AFAIK nothing in the standard says that `sizeof(int[10]) != sizeof(int*)`.

**Comment by knatten** [comment]
That's a very good point! It is of course extremely unlikely, but since we're only asking about the standard, your point holds. I suggest we remove `get_size_3` from the question.

I've emailed the original author of the question to get his view too.

**Comment by xfix** [comment]
Was tricked by that one too.

**Comment by bogiord** [comment]
The comment in the code says `//Assume sizeof(int*) != 10`, but what we actually want to assume is that `sizeof(int*) != sizeof(int[10])`.

**Comment by knatten** [comment]
@bogiord I don't understand why you want to make that change, can you explain a bit more?

**Comment by bogiord** [comment]
Even if `sizeof(int*) != 10`, it's still possible that `sizeof(int*) == sizeof(int[10])` (unless `sizeof(int) == 1`), which means that we can still get the output `111` even with the assumption as written.

**Comment by knatten** [comment]
Ah, of course. I've updated the question now.
