### ISSUE TITLE
Question #121's explanation

### ISSUE THREAD

**Issue by timsong-cpp** [knatten/cppquiz#66]
> So first `a` is evaluated, yielding the value 10 which is then discarded. 

The LHS of the comma operator is a discarded-value expression. Since `a` is not volatile-qualified, no lvalue-to-rvalue conversion is performed ([expr]/11), so it can't "yield[] the value 10".

**Comment by knatten** [comment]
Thanks, you are of course right. I'll change

> So first `a` is evaluated, yielding the value `10` which is then discarded. Then `b` is evaluated, yielding the value `20`, which is then the resulting value of the `(a, b)`, and assigned to `x`.

to

> The right operand here being `b`, with the value `20`. This is then the resulting value of the expression `(a, b)`, and `20` is assigned to `x`.

The full explanation is then

> The comma operator is applied on two expressions: `a` and `b`.
> 
> According to §5.18¶10 in the standard: "A pair of expressions separated by a comma is evaluated left-to-right; the left expression is a discarded-value expression (...) The type and value of the result are the type and value of the right operand"
> 
> The right operand here being `b`, with the value `20`. This is then the resulting value of the expression `(a, b)`, and `20` is assigned to `x`.
