### ISSUE TITLE
Constructor name is used wrongly in q5

### ISSUE THREAD

**Issue by vinothcse123** [knatten/cppquiz#67]

**Comment by knatten** [comment]
Hi, can you please elaborate? Is it [this question](http://cppquiz.org/quiz/question/5) you're referring to? What exactly is wrong with it?

**Comment by vinothcse123** [comment]
Am sorry.
Raised wrongly.
Just close the defect
Sorry for inconvenience

**Comment by knatten** [comment]
Will do! :)
