### ISSUE TITLE
Question #29 typo

### ISSUE THREAD

**Issue by dingouerinitx** [knatten/cppquiz#68]
b.foo() instead of b.bar() in main? BTW a big thank you for the quiz ^^

**Comment by knatten** [comment]
While that would certainly be a valid question too, I think the question is better in its current form.

Now, all calls to `foo` come from methods inside `A`, which emphasises the point of the question: At which points in the objects lifecycle are virtual functions considered.

**Comment by dingouerinitx** [comment]
Ah I see. Thanks for throwing light on that. So then I'll close that non issue then ;). Thx.
