### ISSUE TITLE
Q 140 assumes sizeof results

### ISSUE THREAD

**Issue by henke37** [knatten/cppquiz#71]
The `sizeof` operator allows the implementation to decide what it feels is the best result. Without knowing the implementation, the question can't be answered consistently.

**Comment by knatten** [comment]
Thanks for your comment!

The only scenario I can think of in which this could be ambiguous, is if the size of a pointer to int is `10`, which is extremely unlikely. Or can you think of any other cases?

Anyway, the question is not 100% unambiguous, which is unfortunate. Maybe we could solve this by simply adding an assumption to the question:
> Assume `sizeof(int*) != 10`

What do you think?

**Comment by knatten** [comment]
I went for that solution. I don't like having assumptions in the questions, but I like this one so much that I made an exception.
