### ISSUE TITLE
Question 145

### ISSUE THREAD

**Issue by maxvtikhomirov** [knatten/cppquiz#73]
Answer 13 is correct, it says it's wrong and "hints" at return value optimisation.
![capture](https://cloud.githubusercontent.com/assets/26819562/25838862/92484e9c-34ae-11e7-95b1-72faa23f1822.PNG)

**Comment by knatten** [comment]
This output of this program is implementation defined, and might vary between compilers. See the full explanation here http://cppquiz.org/quiz/question/145?result=US&answer=&did_answer=Answer
