### ISSUE TITLE
Q: 133 - Suggestion: Make inheritance of A "public virtual"

### ISSUE THREAD

**Issue by darren-repository** [knatten/cppquiz#75]
When compiling Q.133 in VC2017 I received the following output from the compiler:
>> warning C4594: class 'D' can never be instantiated - indirect virtual base class 'A' is inaccessible
>> note: 'A' is a private base class of 'B'
>> warning C4624: 'D': destructor was implicitly defined as deleted
>> error C2280: 'D::~D(void)': attempting to reference a deleted function
>> note: compiler has generated 'D::~D' here
>> note: 'D::~D(void)': function was implicitly deleted because the destructor of indirect virtual base class 'D' is inaccessible

When I changed the inheritance of A to "public virtual" for B and C the program compiled and ran without issue.

**Comment by knatten** [comment]
Good point! I wonder why clang doesn't give warnings or errors about this. I've updated the question now. Thanks for reporting!
