### ISSUE TITLE
question #145 invalid as of C++17

### ISSUE THREAD

**Issue by valentingalea** [knatten/cppquiz#76]
The correct answer as of C++17 for #145 is "13" not "implementation defined". RVO of that form has been made mandatory.

Consider changing the preamble "As of .."

**Comment by knatten** [comment]
Thanks for the comment @valentingalea! The entire content of cppquiz will need to be updated to C++17 at some point.

Which preamble are you talking about?

**Comment by valentingalea** [comment]
"According to the C++11 standard" .. I guess it's technically correct but
as you say, you need updating to 17 for at least some of the questions.

**Comment by knatten** [comment]
I think the preamble works for now. I'll handle updating to C++17 in #77.
