### ISSUE TITLE
Question about Qustion 152

### ISSUE THREAD

**Issue by xuzhao9** [knatten/cppquiz#78]
The explanation says "Plain char, signed char, and unsigned char are three distinct types".
However in Q151 it says "It is implementation-defined whether a char object can hold negative values.
"

So my question is, is std::is_signed<char>::value guaranteed to be zero, or is it implementation-defined?

**Comment by knatten** [comment]
I'm not sure I understand your question, but `std::is_signed<char>::value` is implementation defined.

It is up to the implementation whether `char` can hold negative values. However, regardless of whether `char` is signed or not, the _type of `char`_ is always distinct from the type of both `signed char` and `unsigned char`.

**Comment by xuzhao9** [comment]
Oh I understand. Thanks for your clarification!

**Comment by knatten** [comment]
Happy to help! :)
