### ISSUE TITLE
Wrong quote in the explanation for question #126

### ISSUE THREAD

**Issue by bogiord** [knatten/cppquiz#80]
The answer quotes §3.4¶14; this is not the paragraph you're looking for. It refers to namespaces, not classes. `x` is first declared in a class scope, not in a namespace scope.

The relevant one is paragraph 13 above: "A name used in the deﬁnition of a static data member [...]". And the section number is actually 3.4.1.

Also relevant is [class.static.data]/2: "[...] The initializer expression in the deﬁnition of a static data member is in the scope of its class [...]".

**Comment by knatten** [comment]
Thanks! I suggest changing the explanation from 

> §3.4¶14 states ""if a variable member of a namespace is defined outside of the scope of its namespace then any name that appears in the definition of the member after the declarator-id) is looked up as if the definition of the member occurred in its namespace..."

> Using the class scope to specify the static member `x` changes the initial lookup-path for `foo()`. The scope at which `x` exists(that is, the enclosing namepsace where `x` was declared) is first searched before considering the surrounding namespaces.


to

> §3.4.1¶13 states "A name used in the definition of a static data member of class `X` (...) is looked up as if the name was used in a member function of `X`."

> Even though the call `foo()` occurs outside the class, since `foo` is used in the definition of the static data member `foobar:x`, it is looked up as if `foo()` was called in a member function of `foobar`. If `foo()` was called in a member function of `foobar`, `foobar:foo()` would be called, not the global `foo()`.

What do you think? I've also emailed the original author of this question to get their opinion.

**Comment by iamOgunyinka** [comment]
I'm no expert, I actually posted the question on someone's behalf, so, as long as the newly referenced text is correct, I'm down for it.

**Comment by bogiord** [comment]
That's a very clear explanation. I like it.

**Comment by knatten** [comment]
Thanks a lot for an excellent bug report! :) I've updated [the answer](http://cppquiz.org/quiz/question/126/change/?result=OK&answer=11&did_answer=Answer) now.
