### ISSUE TITLE
Unclear explanation for question #1

### ISSUE THREAD

**Issue by bogiord** [knatten/cppquiz#81]
One could read the explanation as "overload resolution chooses `f(int&)` as a better match over `f(const int&)`", which is not what happens. Explicit specializations don't participate in overload resolution. According to [temp.over]/1, there's only one candidate for overload resolution, the declaration of the specialization `void f<int>(int&)`, obtained using template argument deduction.

`template<> void f(const int &i)` is actually `template<> void f<const int>(const int &i)`, an explicit specialization of `template<class T> void f(T &i)` for `T = const int`. Since template argument deduction for the call `f(i)` deduces `T = int`, the explicit specialization doesn't match at all, and `void f<int>(int&)` is instantiated from the template.

If the second declaration were something like `void f(const int &i)`, a non-template function, then it would participate in overload resolution alongside the specialization of the template.

**Comment by knatten** [comment]
Yeah, this can be interpreted wrongly, I agree. What about something like this:

> For the call `f(i)`, since the type of `i` is `int`, argument deduction deduces `T = int`.
>
> The explicit specialization `template <> void f(const int &i)` has `T = const int`, which is not the same type as `int`, so it doesn't match.
>
>Instead, `template <class T> void f(T &i)` with `T = int` is used to create the implicit instantiation `void f<int>(int&)`.

**Comment by knatten** [comment]
Done! Thanks for reporting.
