### ISSUE TITLE
Change from section numbers to section names?

### ISSUE THREAD

**Issue by knatten** [knatten/cppquiz#95]
Instead of quoting e.g. _§10.2¶5_, quote _[class.member.lookup]¶5_. This will make it easier to update questions when moving to a newer version of the standard (see #77). It will also make it easier to find the relevant section for people who are looking stuff up in another version of the standard than the one targeted by us (currently C++11).

However, I personally find it easier to look stuff up by section number when I have the table of contents opened in my pdf viewer. So maybe using both is an even better idea? Something like _[class.member.lookup]§10.2¶5_.

I'm very much open to opinions on this matter!

**Comment by asbjornu** [comment]
Both would be nice.

**Comment by knatten** [comment]
Suggestion from [@KrzaQ](https://twitter.com/KrzaQ2)

> Use section names. Ideally, make a copy of Eelis's website (or perhaps bind to specific Nxxxx like from timsong-cpp.github.io/cppwp/n4659/ ) and link there directly

**Comment by knatten** [comment]
Decide on going for this format:

> According to \[class.member.lookup\](§10.2)¶5 in the C++11 standard:
> Lorem ipsum

**Comment by knatten** [comment]
Need to update these questions:

```
 for q in [" - [ ] " + str(q.id) for q in models.Question.objects.exclude(state='REF').order_by('pk')]:
  print q
```

 - [ ] 1
 - [ ] 2
 - [ ] 3
 - [ ] 4
 - [ ] 5
 - [ ] 6
 - [ ] 7
 - [ ] 8
 - [ ] 9
 - [ ] 11
 - [ ] 12
 - [ ] 13
 - [ ] 14
 - [ ] 15
 - [ ] 16
 - [ ] 17
 - [ ] 18
 - [ ] 24
 - [ ] 25
 - [ ] 26
 - [ ] 27
 - [ ] 28
 - [ ] 29
 - [ ] 30
 - [ ] 31
 - [ ] 32
 - [ ] 33
 - [ ] 34
 - [ ] 35
 - [ ] 37
 - [ ] 38
 - [ ] 40
 - [ ] 41
 - [ ] 42
 - [ ] 43
 - [ ] 44
 - [ ] 45
 - [ ] 46
 - [ ] 47
 - [ ] 48
 - [ ] 49
 - [ ] 50
 - [ ] 51
 - [ ] 52
 - [ ] 105
 - [ ] 106
 - [ ] 107
 - [ ] 108
 - [ ] 109
 - [ ] 110
 - [ ] 111
 - [ ] 112
 - [ ] 113
 - [ ] 114
 - [ ] 115
 - [ ] 116
 - [ ] 117
 - [ ] 118
 - [ ] 119
 - [ ] 120
 - [ ] 121
 - [ ] 122
 - [ ] 123
 - [ ] 124
 - [ ] 125
 - [ ] 126
 - [ ] 127
 - [ ] 128
 - [ ] 129
 - [ ] 130
 - [ ] 131
 - [ ] 132
 - [ ] 133
 - [ ] 134
 - [ ] 135
 - [ ] 140
 - [ ] 141
 - [ ] 144
 - [ ] 145
 - [ ] 146
 - [ ] 147
 - [ ] 148
 - [ ] 151
 - [ ] 152
 - [ ] 153
 - [ ] 157
 - [ ] 158
 - [ ] 159
 - [ ] 160
 - [ ] 161
 - [ ] 162
 - [ ] 163
 - [ ] 167
 - [ ] 168
 - [ ] 169
 - [ ] 174
 - [ ] 175
 - [ ] 176
 - [ ] 177
 - [ ] 178
 - [ ] 179
 - [ ] 180
 - [ ] 181
 - [ ] 183
 - [ ] 184
 - [ ] 185
 - [ ] 186
 - [ ] 187
 - [ ] 188
 - [ ] 189
 - [ ] 190
 - [ ] 191
 - [ ] 192
 - [ ] 193
 - [ ] 194
 - [ ] 195
 - [ ] 196
 - [ ] 197
 - [ ] 198
 - [ ] 199
 - [ ] 200
 - [ ] 201
 - [ ] 202
